### ISSUE TITLE
Support for pg prefer for ssl

### ISSUE THREAD

**Issue by kutysam** [brianc/node-postgres#2775] opened 2022-07-22 16:37 UTC
According to https://www.postgresql.org/docs/current/libpq-ssl.html there are different modes of ssl connectivity (if we need or not)

34.19.3. Protection Provided in Different Modes

I would like to check if prefer is enabled on this library. From what i see, it is either true or false.

If that is the case, I don't think the server can function without a downtime. 
if it is prefer, and the db connection fails, it will probably fallback to non-ssl.
And if i enable ssl, it will probably restart the connection to ssl.

With just being true / false, I don't think this can be done.

**Comment by charmander** [comment] 2022-07-22 18:12
Duplicate of #2720

**Closed by charmander** 2022-07-22 18:12 UTC
