### ISSUE TITLE
loopback-connector-postgresql  doesn't connect with Node V. - 14.3.0 

### ISSUE THREAD

**Issue by manthan-sf** [brianc/node-postgres#2230] opened 2020-05-30 07:29 UTC

**Comment by charmander** [comment] 2020-05-30 22:36
pg ≤ 8.0.2 doesn’t support Node 14. Please upgrade to pg 8.2.1.

**Comment by charmander** [comment] 2020-05-30 22:36
Duplicate of #2181

**Closed by charmander** 2020-05-30 22:36 UTC
