### ISSUE TITLE
Unhandled 'error' event thrown when the connection password doesn't match

### ISSUE THREAD

**Issue by david-rouchet** [brianc/node-postgres#746] opened 2015-03-11 20:48 UTC
When I connect to an existing database with the connect username but the wrong password, I got an unhandled exception using the following code. The parameter err is set, but the exception is still thrown.

````
pg.connect(dbURL, function(err, client, done) {
  if(err) {
    return console.error('error fetching client from pool', err);
  }
  client.query('SELECT $1::int AS number', ['1'], function(err, result) {
    //call `done()` to release the client back to the pool
    done();

    if(err) {
      return console.error('error running query', err);
    }
    console.log(result.rows[0].number);
    //output: 1
    client.end();
  });
});
````

**Comment by brianc** [comment] 2015-03-11 20:49
That's odd...I'm pretty sure we have a test for that in the unit tests.
What version of PG & node-postgres?

**Comment by david-rouchet** [comment] 2015-03-11 20:58
pg version is 4.3.0, node-js is 0.10.31 and postgreSQL server is 9.3.5

**Comment by david-rouchet** [comment] 2015-03-19 15:43
Hi there,
any clue, bug fiix or suggestion on this issue?

**Comment by tsoule** [comment] 2015-04-02 21:18
Hi, I am encountering the same issue when using an incorrect username. My callback to pg.connect is executed with a "password authentication failed..." error, which I deal with. However, an ECONNRESET error is subsequently emitted, hitting [this line](https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L59), and there is no way for me to handle it. I tested with node-postgres (not native) 4.3.0 on Windows and Mac. I am running PostgreSQL 9.4 on Windows.

**Comment by david-rouchet** [comment] 2015-04-02 21:46
I still have the same issue and this become a concern for the project I'm working on...

**Comment by vitaly-t** [comment] 2015-04-06 06:15
+1
Happens here always when the password is incorrect.

**Comment by kamushkin** [comment] 2015-05-13 11:09
+1
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```
happens when calling pg.connect with either user, password or db incorrect.
windows7, node v0.10.22, PostgreSQL 9.4.1, pg 4.3.0

**Comment by david-rouchet** [comment] 2015-05-13 13:34
So far no fix has been proposed. Does anywone see a way to workaround this issue? We still have a project going on and which is fragilized by this error.

**Comment by brianc** [comment] 2015-05-13 17:00
I think the best work around would be to submit a failing test or even better some code to fix the issue in a PR. :wink: 

I can't reproduce the issue locally - the error is correctly passed to the callback with both a bad host or bad username.

I also already have test cases covering this issue and they pass:

https://github.com/brianc/node-postgres/blob/master/test/integration/client/error-handling-tests.js#L136
https://github.com/brianc/node-postgres/blob/master/test/native/connection-tests.js#L5

**Comment by kamushkin** [comment] 2015-05-14 12:40
Looks like the right test (user/password) is commented out (?) -
https://github.com/brianc/node-postgres/blob/master/test/integration/client/error-handling-tests.js#L148

The one you refer to is about invalid host (means no response instead of refusing connection) -
https://github.com/brianc/node-postgres/blob/master/test/integration/client/error-handling-tests.js#L136

Here is also the minimum code to reproduce the issue -

```
var pg = require('pg');

pg.connect('postgres://abc:def@localhost:5432/xyz', function (err, db, done) {
	console.log('connect callback called');
});
```

which produces
```
connect callback called

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

I did not test this with native bindings - possibly the issue is limited to js

**Comment by david-rouchet** [comment] 2015-05-14 13:14
I do agree, the unhandled error occurs when the server can be reached but either the username or the password is incorrect.

Another code example which reproduces this error.

In this example, 'postGres' should be 'postgres'. So if 'postGres' is used instead of 'postgres' the Unhandled exception is raised.

````
var pg = require('pg');
var dbURL = 'postgres://postgres:postGres@192.168.1.81/dbname';

if (0) { // whether this code is activated or not, the error is not catched
  pg.on( 'error', function(err) {
    console.log('do nothing');
  });
}

try {
  pg.connect( dbURL, function(err, client, done) {

    if ( err ) {
      return console.error( 'Connection error handled, code: ', err.code);
    }
    else {
      if ( client ) {
        console.error( 'Connection succeed on ', client.host );
      }
      else {
        console.error( 'Connection done but client is null or undefined' );
      }
    }
  });
}
catch( err ) {
  console.log( 'DB Connect error handled');
}
````

**Comment by vitaly-t** [comment] 2015-05-23 16:53
+ 1000,000

The same error is thrown if we pass an invalid connection:

```javascript
pg.connect("bla-bla");
```

It's been way too long for such a critical issue to just sit here and nothing being done about it. Very frustrating. I have a number of tests now for [pg-promise](https://github.com/vitaly-t/pg-promise) commented out because of this error, which just kills jasmine framework that I'm using for testing.

**Comment by brianc** [comment] 2015-05-29 14:21
@vitaly-t The great thing about open source is if you're having frustration with something you can submit a patch & make the code better for everyone!  I tried to reproduce the issue locally and wasn't able to and don't have time right now to dive deep into something that isn't causing me any issues and isn't reproducible on my end.  Do you have the time to put together a pull request with a test and a fix for this?

The minimum code sample submitted by @kamushkin did __not__ throw an error for me and the error was properly handled.

**Comment by vitaly-t** [comment] 2015-05-29 14:52
@brianc, it's all doable, I'm just pressed for time, same as yourself, struggling to make time to maintain my own library :)

Anyhow, the issue here goes outside **node-postgres**, if you Google for it:
```javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```
you will see how many people complain about the same error, just related to different libraries. The issue is within one of the sub-libraries that are used. I did take my time to narrow it down somehow, but without luck so far.

I don't understand how the issue doesn't manifest itself. I've tried it on 3 computers at this point, and can see it happen on each of them. Try reproducing the issue on other computers.

Also, as was pointed out earlier, the key tests for this are commented out, which is the key to showing the problem. Un-commenting those tests would be a good starting point.

**Comment by sehrope** [comment] 2015-05-31 12:17
I'm not able to reproduce this either. I tried the sample code and it works fine with v4.3.0 on both my Mac and Linux desktop (Ubuntu 14.04). Both were run using only the JS bindings (not the native ones).

**Comment by kamushkin** [comment] 2015-05-31 16:37
To reproduce the issue the host:port combination should be correct, i.e. you should actually have postgres running on localhost:5432 for the code above. It does not happen when the hostname or port is incorrect. 

However the following also triggers the same exception for me -

```
var pg = require('pg');

pg.connect('bla-bla', function (err, db, done) {
    console.log('connect callback called');
});
```

win7, node v0.10.22, PostgreSQL 9.4.1, pg 4.3.0

**Comment by david-rouchet** [comment] 2015-06-01 14:02
Unlike mention @kamushkin, the exception happens to me when either the login name or password is NOT correct. However, I noticed that @sehrope is doing his test on Linux/Mac platform whereas @kamushkin and myself on Windows (7).

**Comment by vitaly-t** [comment] 2015-06-03 13:22
I'm developing on Windows 8.1 64-bit, is where I see the problems.

**Comment by vitaly-t** [comment] 2015-06-07 15:06
@brianc 

I have found the problem :)

When you introduced connection pool, you forgot something important about `EventEmitter`, namely how it handles special event `error`, although this goes beyond the connection pool also. When your custom type doesn't provide a handler for event `error`, it is automatically converted into `uncaughtException` by `EventEmitter`.

In cases that were under consideration:
* Invalid connection string
* Invalid user name
* Invalid password

there was event `error` emitted by your library, which without any handler on the corresponding objects is turned into `uncaughtException` by `EventEmitter`. Those corresponding objects in your library are `Client` and `Connection`.

What you were supposed to do is to provide an empty trap for event `error` on each of those objects. If you Google for the error being thrown:
```
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```
you will find many other examples of people running into the same and finding the same solution in the end.

In order to fix the issue, you need to add the following code:
```javascript
this.on('error', function () {
    // prevent EventEmitter from turning event
    // `error` into `uncaughtException`;
});
```
at the very beginning of:
 1.  `Client.prototype.connect = function(callback) {`, - in file **client.js**
 2.  `Connection.prototype.connect = function(port, host) {`, - in file **connection.js**

And that is it.

**Comment by brianc** [comment] 2015-06-07 15:13
I appreciate you looking into this, but providing an empty trap for the `error` event on `EventEmitter` instances is *not* the right approach.  This swallows potentially catastrophic errors without any warning or notice of any kind.  The correct thing to do is in fact let the `EventEmitter` instances crash the process if they don't have an `error` event listener added by the _consuming library_.  The problem is here a bit more complicated...because node-postgres accepts methods with callbacks it attempts to temporarily subscribe to and handle internal `error` events when a callback is provided and might expect the error. Something is going on in the particular instance of a bad password where *2* error events are getting emitted or something, and internally node-postgres is only handling one.  The problem is *I cannot reproduce this locally* no matter what I try.  I don't have access to a windows machine, and don't really test on windows myself.  If someone who can actually reproduce the error will step up with a pull request to address the issue - I'm guessing at the end of the day the pull request will be 1-2 lines tops - I will happily merge & push a new version, otherwise I've done as much as I can on this..

**Comment by vitaly-t** [comment] 2015-06-07 15:23
@brianc , the core problem is your connection pool, because it hides `Client` and `Connection` that emit event `error`, which you cannot do. This is the design issue. And my solution is one to avoid changes in the connection pool protocol.

If you want event `error` to propagate further, you need to change the protocol in such a way that even though one uses the connection pool you'd still have access to the corresponding instances of `Client` and `Connection`, so you can inject `error` handler.

THE IMPORTANT PART

You said you don't want catastrophic errors swallowed with those event traps. But they aren't! Your error handling logic catches the right errors and provides the correct error notification in the callback function of `function (err, client, done)`, so all those errors are reported correctly.

Why my change really effects - to avoid the situation when there are no `error` handlers on those types at all. It all still works because `error` is sent to every handler instance.

So, you are safe to make the change that was suggested.

I have comprehensive tests here that confirm validity of the change, and you should be able to test it also.

**Comment by brianc** [comment] 2015-06-07 15:33
Client errors should be handled by the pool and re-emitted there already:

https://github.com/brianc/node-postgres/blob/master/lib/pool.js#L31

Putting a no-op error handler that swallows any errors at all is 100% no go.  If errors aren't being propagated out to a place where the user can handle them, that's a problem for sure and I'd love a PR addressing where this might be happening, but swallowing them internally unfortunately isn't a option.

...error handling is hard! :smile:

**Comment by vitaly-t** [comment] 2015-06-07 15:46
@brianc ,

As I wrote earlier, you misinterpret the event trap thinking of it as swallowing valuable information. It doesn't. When `EventEmitter` receives event `error`, it checks for all existing `error` handlers on the right object and sends it to every one of them. It is only when it doesn't see a single handler for event `error` it turns the event into `uncaughtException`, saying in its own way that you've gottta have at least one `error` handler there somewhere, since it is being emitted by your code.

At the same time, your statement about uncontrolled `error` being emitted somewhere else holds true, but if you think the problem is in your own code somewhere, it might not be quite the case. See the error once again:
```
   at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```
That is the complete stack, by the way, which suggests the `error` is sent outside of your control altogether, which means there is nothing you can do, except provide a generic handler for every `error` that's not part of your own library.

Please research the error message, there are plenty of similar discussions, and the same solution as one I offered.

**Comment by vitaly-t** [comment] 2015-06-07 16:16
@brianc 

Just to give you an idea of what the stack looks like when those errors occur, I modified those two handlers into:
```javascript
Client.prototype.connect = function(callback) {

    this.on('error', function(err){
        console.log('CLIENT: ************************************');
        console.log(err.stack);
    });
```
and
```javascript
Connection.prototype.connect = function(port, host) {

    this.on('error', function(err){
        console.log('CONNECTION: ************************************');
        console.log(err.stack);
    });
```
And after I run all of my tests, they output the following:
```
CONNECTION: ************************************
Error: getaddrinfo ENOTFOUND unknown
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
CONNECTION: ************************************
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
CONNECTION: ************************************
error: password authentication failed for user "Vitaly"
    at Connection.parseE (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.js
:539:11)
    at Connection.parseMessage (D:\NodeJS\pg-promise\node_modules\pg\lib\connect
ion.js:366:17)
    at Socket.<anonymous> (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.j
s:110:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
CONNECTION: ************************************
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
CLIENT: ************************************
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
CONNECTION: ************************************
error: password authentication failed for user "somebody"
    at Connection.parseE (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.js
:539:11)
    at Connection.parseMessage (D:\NodeJS\pg-promise\node_modules\pg\lib\connect
ion.js:366:17)
    at Socket.<anonymous> (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.j
s:110:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
CONNECTION: ************************************
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
CLIENT: ************************************
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
CONNECTION: ************************************
error: password authentication failed for user "postgres"
    at Connection.parseE (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.js
:539:11)
    at Connection.parseMessage (D:\NodeJS\pg-promise\node_modules\pg\lib\connect
ion.js:366:17)
    at Socket.<anonymous> (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.j
s:110:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
CONNECTION: ************************************
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
CLIENT: ************************************
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
CONNECTION: ************************************
error: relation "unknowntable" does not exist
    at Connection.parseE (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.js
:539:11)
    at Connection.parseMessage (D:\NodeJS\pg-promise\node_modules\pg\lib\connect
ion.js:366:17)
    at Socket.<anonymous> (D:\NodeJS\pg-promise\node_modules\pg\lib\connection.j
s:110:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```
If this in anyway helps you see the issue, great, because it doesn't help me at all.

**Comment by vitaly-t** [comment] 2015-06-07 17:42
@brianc 

The 3 tests in question seem to behave very differently on Linux...

when passing `bla-bla` for connection string, i'm getting error:
```javascript
{
    name: 'error',
    length: 85,
    severity: 'FATAL',
    code: '3D000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'postinit.c',
    line: '775',
    routine: 'InitPostgres'
};
```
when i'm passing an invalid user name, i'm getting error:
```javascript
{
    name: 'error',
    length: 93,
    severity: 'FATAL',
    code: '28000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'miscinit.c',
    line: '433',
    routine: 'InitializeSessionUserId'
}
```
and when i'm passing an invalid password, the call succeeds, i.e. it doesn't return an error at all. In my case my Linux test server doesn't require any password, so maybe it got something do with that, i.e. the password is ignored when it is not required?

I'd like to know your interpretation on the matter.

**Comment by david-rouchet** [comment] 2015-06-08 13:40
@brianc 

Following the @vitaly-t test, I've made some investigations around this and found the following:

in the lib's client code, for the connection, the code is the following

````
con.on('error', function(error) {
    if(self.activeQuery) {
      var activeQuery = self.activeQuery;
      self.activeQuery = null;
      return activeQuery.handleError(error, con);
    }
    if(!callback) {
      return self.emit('error', error);
    }
    callback(error);
    callback = null;
  });
````
When an incorrect password, username of host is provided, as suggested @brianc two errors are thrown. However, the code set the callback to null after catching the first connection error (incorrect connection string error), therefore when the second error (ECONNREST) is thrown, the line `return self.emit('error', error);` is executed and because the client doesn't have any handler on 'errror', this second exception is not hanled at all. 

Note that the client doesn't have any handler first because there is none in the lib code and also because when `pg.connect( dbURL, function(err, client, done) {...` is called, the function returns client = null when an error occors, thus the caller cannot set one either, anyway.

As a test, commenting the line `callback = null;` solves the problem, although this is probably not the rigth solution. I presume it would take few minutes for @brianc to fix this issue as you wrote this code initially. I believe one approach would be to mute this second one (on account this is actually a ECONNRESET - because it is a consequence of the bad connection string) or forward this second one to the pg object.

**Comment by brianc** [comment] 2015-06-08 15:59
I think the right approach is to forward the second one up to the `pg`
object when the client is pooled.  I don't think its ever the right idea to
just gobble up an error.

**Comment by vitaly-t** [comment] 2015-06-08 16:19
@brianc you will end up in a situation where invalid server or database name are handled completely different from how invalid connection/user/password are handled. This shouldn't be the case.

**Comment by mtomy** [comment] 2015-07-06 11:46
Same unhandled error event happens while performing query on connection returned from pool if connection was closed after pool gave it, but before query was performed. So I can not guarantee that postgres restart will not crash my app with unhandled exception error.

@brianc I think it is crucial to describe error handling deeply in node-postgres documentation. Give some examples.

**Comment by vitaly-t** [comment] 2015-07-06 12:10
@mtomy в моем профайле есть библиотека для решения многих проблем этой библиотеки, теска! :)

**Comment by mtomy** [comment] 2015-07-06 12:53
@vitaly-t спасибо! попробую)

**Comment by oliversalzburg** [comment] 2015-08-24 13:57
We're suffering from exactly this issue as well, so I just spent some time on analyzing what is going wrong here.

1. We're calling `pg.connect()`, which creates a new pool.
2. pg calls `pool.connect()` to connect the pool.
3. The pool creates a new client, and instantly invokes `client.connect()`. Here it is assumed that any errors are handled through the callback that is provided to `client.connect()`. This assumption will not hold true.
4. client will attempt to establish a connection and registers an `error` event handler on the connection as well as a generic `data` listener through `attachListeners` (we're not connecting over SSL, so the listener attachment is not delayed. When connecting over SSL, listener attachment is delayed until data is received for the first time. A potential source for bugs IMHO).
5. The connection will fail, because I supplied invalid credentials.
6. The `data` listener is invoked, for a message of the `error` type. This is bubbled up as an `error` event, which is ultimately handled in the `error` handler in `client`. This error handler specifically checks if a callback exists, calls it and then forgets about it (`callback = null`). This sets the whole error handling chain for unsuccessful connects in motion and, finally, my callback from the `connect()` call in 1. is called.
7. Now that the whole error handling chain is rendered useless, the connection will raise an `error` event. This is bubbled up to the point where we checked if a valid callback exists. No valid callback exists anymore, so the error is bubbled up further. At this point, there is no `error` event handler (because none was ever registered between instantiating `client` and calling `client.connect`. Thus, we end up with an unhandled error event. 
And because the client isn't exposed anywhere, we have no chance to handle the error in our code.

**Comment by oliversalzburg** [comment] 2015-08-24 14:12
So, for us, the solution is as simple as not emitting `error` events from the connection.
```js
if(msg.name !== 'error') {
  self.emit(msg.name, msg);
}
```
In `connection.js` line 109.

**Closed** 2015-09-20 13:36 UTC

**Comment by OferE** [comment] 2016-12-05 13:52
still getting this error on pg version 6.1.0.
Why did u close?

**Comment by OferE** [comment] 2016-12-05 13:55
this is how my code looks like.

I'm getting an exception if the db is just created with no user (in a new db container), even though there is an error retruned by the callback.

Any workaround for this issue?

```
    query: function(queryString, args, callback) {
         pg.connect(connectionString, function(err, client, done) {
            if(err) {
               callback(new Error('error fetching client from pool. ' + err));
               return;
            }
            client.query(queryString, args, function(err, result) {
               //call `done()` to release the client back to the pool
               done();
               if(err) {
                  callback(new Error('Error running the query  ' + queryString + '\nError is: ' + err));
                  return;
               }

               callback(undefined, result.rows);
            });
         });
      }
   };
```

**Comment by wuhuaping** [comment] 2016-12-19 15:27
2016-12-19 22:58:34.412] [ERROR] [default] - Master PoolSpawner Fork 0 died, spawning replacement worker...
[2016-12-19 22:58:34.648] [INFO] [default] - New Relic
[2016-12-19 22:58:34.651] [INFO] [default] - POSIX Not Installed
[2016-12-19 22:58:34.652] [INFO] [default] - Run Workers

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: The password has to be of type "string"
    at RedisClient.auth.RedisClient.AUTH (/root/uNOMP/node_modules/redis/index.js:1038:19)
    at new module.exports (/root/uNOMP/libs/poolWorker.js:23:22)
    at Object.<anonymous> (/root/uNOMP/init.js:76:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
[2016-12-19 22:58:34.667] [ERROR] [default] - Master PoolSpawner Fork 1 died, spawning replacement worker...
^C

**Comment by wuhuaping** [comment] 2016-12-19 15:28
我这是的为什么出现这个问题
不在源文件上解决呢

**Comment by charmander** [comment] 2016-12-21 01:59
Upgrade to pg-pool ≥ 1.6.0.
