### ISSUE TITLE
Syntax error at or near ORDER BY

### ISSUE THREAD

**Issue by Avm07** [brianc/node-postgres#2776] opened 2022-07-28 20:21 UTC
Hello, i am facing an issue with sort(asc/desc) param "order by" parsing by node-postgres lib. Without it working well, a similar query works well in pgAdmin. If define it as a text in query working well too.

```javascript
 const selectPools = `SELECT 
      id,
      code,
      encode(sha256, 'escape') sha256,
      base_token_precision,
      base_token_symbol_code,
      base_token_amount,
      base_token_contract,
      encode(base_token_sha256, 'escape') base_token_sha256,
      quote_token_precision,
      quote_token_symbol_code,
      quote_token_amount,
      quote_token_contract,
      encode(quote_token_sha256, 'escape') quote_token_sha256,
      pool_fee_precision,
      pool_fee_symbol_code,
      pool_fee_amount,
      platform_fee_precision,
      platform_fee_symbol_code,
      platform_fee_amount,
      create_time,
      last_update_time
    FROM adexswap_pools
    ORDER BY id $1 LIMIT $2 OFFSET $3;`;

    log.info('Limit:', limit);
    log.info('Offset:', offset);
    log.info('Sort:', sort);

    const result = await query(selectPools, [sort, limit, offset]);
```

Result:

```javascript
2022-07-28 20:16:04.078  INFO [src/controllers/poolsController.ts:71  getLiquidityPools] Limit: 100 
2022-07-28 20:16:04.079  INFO [src/controllers/poolsController.ts:72  getLiquidityPools] Offset: 0 
2022-07-28 20:16:04.079  INFO [src/controllers/poolsController.ts:73  getLiquidityPools] Sort: ASC 

{
    "success": false,
    "message": {
        "message": "syntax error at or near \"$1\"",
        "length": 92,
        "name": "error",
        "severity": "ERROR",
        "code": "42601",
        "position": "666",
        "file": "scan.l",
        "line": "1176",
        "routine": "scanner_yyerror"
    }
}
```

Lib does not parse SORT option correct in the literal query if I define it like below parsing succeeds.

```javascript
const selectPools = `SELECT 
      id,
      code,
      encode(sha256, 'escape') sha256,
      base_token_precision,
      base_token_symbol_code,
      base_token_amount,
      base_token_contract,
      encode(base_token_sha256, 'escape') base_token_sha256,
      quote_token_precision,
      quote_token_symbol_code,
      quote_token_amount,
      quote_token_contract,
      encode(quote_token_sha256, 'escape') quote_token_sha256,
      pool_fee_precision,
      pool_fee_symbol_code,
      pool_fee_amount,
      platform_fee_precision,
      platform_fee_symbol_code,
      platform_fee_amount,
      create_time,
      last_update_time
    FROM adexswap_pools
    ORDER BY id ` + sort + ` LIMIT $1 OFFSET $2`;
```

**Comment by charmander** [comment] 2022-07-28 23:13
`DESC` is a keyword, not a value that can be a parameter. You do need to create a dynamic query.

**Comment by charmander** [comment] 2022-07-28 23:13
Duplicate of #1734

**Closed by charmander** 2022-07-28 23:13 UTC
