### ISSUE TITLE
Non-existing path OR NULL from JSONB is treated as empty object

### ISSUE THREAD

**Issue by dmiwell** [brianc/node-postgres#3085] opened 2023-10-27 12:25 UTC
After upgrading from `8.11.1 -> 8.11.3`, the following happens:

| id | col |
|--|:---:|
| 1 |  {}  |

```
SELECT col->'path' FROM any WHERE id = 1
```
results to `{}` instead of `null`. For 8.11.1 it is correct and `null`. `'{}'` is passed to JSONB type parser resulting with `{}`.

**Comment by charmander** [comment] 2023-10-29 07:04
This sounds like #3062, but that particular example wouldn’t trigger it. Do you actually have multiple columns with the same name?

**Comment by dmiwell** [comment] 2023-10-30 06:12
No, it's not related to the same name. The only issue I faced with, that is described above, is returning `{}` instead of `null` when non-existing JSONB path is requested.

**Comment by dmiwell** [comment] 2023-10-30 06:17
@charmander got it now. Yes the case is in postgres I have a column named `default_value` and I do 
```
SELECT default_value->'data' AS default_value
```

Tried to rename alias and it works the same way as in 8.11.1

**Comment by charmander** [comment] 2023-10-30 06:28
Duplicate of #3062

**Closed by charmander** 2023-10-30 06:28 UTC
