### ISSUE TITLE
pg/lib/crypto/utils.js giving error because of a outside-of-function return statement

### ISSUE THREAD

**Issue by barisulgen** [brianc/node-postgres#2990] opened 2023-05-30 14:30 UTC
ERROR in ./node_modules/pg/lib/crypto/utils.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\PC\Documents\REPOS\Dert_Projects\dert-cx-dashboard\node_modules\pg\lib\crypto\utils.js: 'return' outside of function. (7:2)

   5 |   // We are on an old version of Node.js that requires legacy crypto utilities.
   6 |   module.exports = require('./utils-legacy')
>  7 |   return
     |   ^
   8 | }
   9 |
  10 | const nodeCrypto = require('crypto')

**Comment by charmander** [comment] 2023-05-30 21:31
Duplicate of #2980

**Closed by charmander** 2023-05-30 21:31 UTC
