### ISSUE TITLE
query.on is not a function

### ISSUE THREAD

**Issue by wayne-o** [brianc/node-postgres#1377] opened 2017-07-19 12:47 UTC
This line: 

https://github.com/brianc/node-postgres/blob/master/lib/client.js#L394

Should be: 

`return query`

Else I get errors using sequelize where query.on is not a function.

Or is this an issue with sequelize and version mismatches?

**Comment by brianc** [comment] 2017-07-19 15:39
duplicate of https://github.com/brianc/node-postgres/issues/1372

sequelize is looking into it - I believe they have a PR pending merge that will fix the issue.

**Closed by brianc** 2017-07-19 15:39 UTC

**Comment by wayne-o** [comment] 2017-07-19 16:19
Brilliant - thanks :)
		
		

		Get Outlook for iOS
	




On Wed, Jul 19, 2017 at 4:39 PM +0100, "Brian C" <notifications@github.com> wrote:












duplicate of #1372


sequelize is looking into it - I believe they have a PR pending merge that will fix the issue.
