### ISSUE TITLE
Connecting to RedShift Fails

### ISSUE THREAD

**Issue by RakeshKulangara** [brianc/node-postgres#1212] opened 2017-02-11 00:23 UTC
```
Unable to connect to the database: { error: permission denied to set parameter "client_min_messages" to "warning"
    at Connection.parseE (/Users/rakesh/code/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/rakesh/code/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/Users/rakesh/code/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

  name: 'error',
  length: 172,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '/home/ec2-user/padb/src/pg/src/backend/utils/misc/guc.c',
  line: '7157',
  routine: 'set_config_option' }
```

PG Version
```
└─┬ pg@6.1.2
  ├── buffer-writer@1.0.1
  ├── packet-reader@0.2.0
  ├── pg-connection-string@0.1.3
  ├─┬ pg-pool@1.6.0
  │ └── object-assign@4.1.0
  ├─┬ pg-types@1.11.0
  │ ├── ap@0.2.0
  │ ├── postgres-array@1.0.2
  │ ├── postgres-bytea@1.0.0
  │ ├── postgres-date@1.0.3
  │ └── postgres-interval@1.0.2
  ├─┬ pgpass@1.0.1
  │ └── split@1.0.0
  └── semver@4.3.2
```
Any ways to get around this issue?

**Comment by charmander** [comment] 2017-02-13 23:44
Could you provide a small script that produces the error, please?

**Comment by manueltimita** [comment] 2017-03-02 03:38
This is an issue similar to https://github.com/jruby/activerecord-jdbc-adapter/issues/403 

> AWS's Redshift is PostgreSQL under the hood, with some features restricted. Trying to use this adapter with Redshift does not work, however, because reading and writing client_min_messages and issuing the SET time zone command is not supported.

I guess a 'feature request' tag is appropriate, if there are plans to make those parameters configurable and thus make node-postgres compatible with Redshift. However, since the target of this library is the vanilla PostgreSQL, maybe a more appropriate course of action would be to just close this issue and refer the OP to specialised tools, such as https://github.com/dmanjunath/node-redshift

**Comment by eudaimos** [comment] 2017-04-14 18:16
@RakeshKulangara are you using this under [sequelize](https://github.com/sequelize/sequelize)?

Because I was trying to connect to Redshift using sequelize and ran into the same issue. Going down the rabbit hole to `pg-connection-string` and it's `parse` function and seeing the whitelisting issue with query string params, but it's not related.

The issue is in sequelize as it's trying to set Timezone here: 
https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L138-L145
I couldn't figure out how to **enable** (set to `true`) the `keepDefaultTimezone` value so I set it raw here
https://github.com/sequelize/sequelize/blob/688dd002b486b77ebd1de5d902c94ab53c70317a/lib/sequelize.js#L199
This then led to a `typearray` datatype issue that's not seemingly resolved although there's a merged PR that "fixes" it here https://github.com/sequelize/sequelize/pull/7266

So I stopped at that point and switched to [node-redshift](https://github.com/dmanjunath/node-redshift) I'm able to query just fine

**Comment by brianc** [comment] 2017-05-24 14:12
Sorry you ran into issues connecting to redshift! I don't think this is related to node-postgres directly as I use node-postgres to connect to it & it looks like node-redshift does as well.

**Closed by brianc** 2017-05-24 14:12 UTC
