### ISSUE TITLE
Still getting same error Connection terminated 

### ISSUE THREAD

**Issue by baninaveen** [brianc/node-postgres#1428] opened 2017-08-26 04:58 UTC
I getting connection terminated error:  Error show Query error: Error: Connection terminated

### userdata.js   >>> new file

`'use strict';
const request = require('request');
const config = require('./config');
const pg = require('pg');
pg.defaults.ssl = true;

const pool = new pg.Pool(config.PG_CONFIG);

module.exports = {

    storeUserData: function(dataOne, dataTwo, userId) {    
        pool.query(`
            INSERT INTO public.user_izo_data (psy_no, dest_no, fb_id)
                SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT id FROM user_izo_data)
        `, [dataOne, dataTwo, userId])
            .catch(console.error);
    },
};`

### package.json
` "author": "",
  "license": "ISC",
  "dependencies": {
    "apiai": "^2.0.5",
    "body-parser": "^1.15.1",
    "exact": "^0.8.0",
    "express": "^4.13.4",
    "pg": "7.0.2",
    "request": "^2.72.0",
    "save": "^2.3.1",
    "uuid": "^2.0.3"`

### app.js  >>> main app
`'use strict';

const apiai = require('apiai');
const config = require('./config');
const express = require('express');
const crypto = require('crypto');
const bodyParser = require('body-parser');
const pg = require('pg');
const request = require('request');
const app = express();
const uuid = require('uuid');
const user = require('./user');
const userdata = require('./userdata');

pg.defaults.ssl = true;`

### app.js >>> call the storeUserData function 

// Store Info into DB POSTgres
userdata.storeUserData(fullData, desData, sender);

I already raise ticket earlier 2 days ago. but it didn't solved. https://github.com/brianc/node-postgres/issues/1427

**Comment by charmander** [comment] 2017-08-26 13:54
Does the error still occur on pg 7.2.0?

**Comment by sehrope** [comment] 2017-08-26 14:10
The INSERT SQL is incorrect as well. The NOT EXISTS clause is checking if *any* id exists. Once you have one record in that table you'll never INSERT any new users. You  want something like the following which checks if that one specific id exists:

```
INSERT INTO public.user_izo_data
(psy_no, dest_no, fb_id)
SELECT $1, $2, $3
WHERE NOT EXISTS (SELECT 1 FROM user_izo_data z WHERE z.id = $3)
```

... though even that has a race condition. The real way to do this on a modern PostgreSQL installation is to use INSERT ON CONFLICT: https://www.postgresql.org/docs/current/static/sql-insert.html#SQL-ON-CONFLICT

Separately, if you're receiving `"Connection terminated"` errors then you probably have a `.end()` somewhere else in your code that is closing the pooled connections. The other issue you linked to (#1427) has a `pool.end()` at the end which would shut down the pool. It may be caused by that.

**Comment by baninaveen** [comment] 2017-08-27 10:50
Now it works.   but now I getting to error for getting data from tables. 

`readUserData: function(callback, userId) {
        pool.connect(function(err, client, done) {
            if (err) {
                return console.error('Error acquiring client', err.stack);
            }
            client
                .query(
                    'SELECT psy_no FROM public.user_izo_data WHERE fb_id=$1',
                    [userId], done);
                    function(err, result) {
                        if (err) {
                            console.log(err);
                            callback('');
                            done(err);
                        } else {
                            callback(result.rows[0]['psy_no']);
                        };
                    };
        });
    }`

**Comment by abenhamdine** [comment] 2017-08-27 11:47
Please post your error message, not only your code.

**Comment by baninaveen** [comment] 2017-08-27 13:49
SyntaxError: Unexpected token (
 function(err, result) {

Here I call this function `var navDa = userdata.readUserData(`${psy_no}`, sender);`

**Comment by charmander** [comment] 2017-08-27 14:09
That’s a syntax error in your code, and nothing to do with this driver.

**Closed by charmander** 2017-08-27 14:09 UTC
Labels: waiting for more info
