### ISSUE TITLE
Unhandled execption when postgreSQL server stops

### ISSUE THREAD

**Issue by david-rouchet** [brianc/node-postgres#683] opened 2014-11-17 20:57 UTC
An Unhandled 'error' event is generated when a client is connected to the database and the server is stopped. The documentation does not specify if there is a way to handle this case.

**Comment by sibson** [comment] 2015-03-16 22:12
I've just hit a similar issue, due to connections being terminated.  

We were expecting client.on('error') to be able to handle terminated connection but the process was being killed due to the uncaught exception.  If you setup a pg.on('error') that does nothing then the client handler will be called.

I would have expected that setting up client.on('error') would be sufficient and pg.on('error') should not be required.

```node
var pg = require('pg');

if (1) { // if we don't do this we get an Unhandled 'error' event and client.on('error') isn't called
    pg.on('error', function(err) {
        console.log('do nothing');
    });
}

var client = pg.connect(function(err, client) {
    if (err) {
        console.log('ERROR: failed to connect', err);
        return;
    }

    console.log('Connected');
    // use select pg_terminate_backend(pid) to kill this connection

    client.on('error', function(err) {
        console.log('Client error', err);
    });
});
```

**Comment by flesler** [comment] 2015-06-02 15:40
Hi, I'm binding to the global error event (on pg) and still errors bubble up and crash the process.
Was expecting pg.on('error', ...) to stop that from happening.

I'm using PG 4.1.1. I know it's not the latest but I don't like packages changing on me without testing. I looked for a changelog to see if this was fixed from 4.1.1 to 4.3.0 but couldn't find any.

**Comment by shvydok** [comment] 2016-06-13 10:36
I also have same issue when mongodb server is stopped:

uncaughtException: connect ETIMEDOUT

it is not handled by client.on('error',..);

Typical use case for it:  db server and node service is in different VMs and node already started but db is not yet or because of some other network issues, so it will good to handle this error not just throw uncaughtException, so we will able to apply some logic.

Thank you.

**Comment by kruser** [comment] 2016-06-13 16:57
I see this problem regularly in this context:

I have multiple scheduled jobs that query our DB independently. Their queries overlap in time. One query will have their exception caught (the one that generates the DB error shown below) while the other will throw an uncaught exception, killing node.

Here is the caught exception
```json
{  
   "name":"error",
   "length":339,
   "severity":"ERROR",
   "code":"XX000",
   "detail":"\n -----------------------------------------------\n error: Disk Full\n code: 1016\n context: node: 0\n query: 9227519\n location: fdisk_api.cpp:350\n process: query0_56 [pid=26878]\n -----------------------------------------------\n",
   "file":"/home/awsrsqa/padb/src/sys/xen_execute.cpp",
   "line":"6198",
   "routine":"pg_throw"
}
```

**Comment by brianc** [comment] 2016-06-21 19:40
Can you submit a self-contained code sample that reproduces this issue? I'm happy to fix it in that case.  Otherwise, I'm not sure what to do as I've not seen this myself.

**Comment by shvydok** [comment] 2016-06-21 22:37
Thank you for follow-up, after some update it is not reproducible anymore
for me.

Ihor.

**Comment by kruser** [comment] 2016-06-24 15:33
> Can you submit a self-contained code sample that reproduces this issue? I'm happy to fix it in that case. Otherwise, I'm not sure what to do as I've not seen this myself.

@brianc - I won't have time to build this anytime soon. So I'm fine if you close it for now. If I'm able to drill into it and create a self contained reproduction I'll submit it.

**Closed as completed** 2017-06-16 22:18 UTC
