### ISSUE TITLE
8.2.1 introduced an error when handling option properties that are objects (still a problem in 8.3.0)

### ISSUE THREAD

**Issue by SamMaxwell** [brianc/node-postgres#2306] opened 2020-08-09 16:49 UTC
the options object that is passed into pg has a property that is an object
 {user:"postgres",database:"dvdrental",options:{appName:"Simplicity",enableArithAbort:false,encrypt:false}}

that used to work in 8.2.0, but ever since 8.2.1 (and still in 8.3.0) we now get the following error

`TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
    at Function.byteLength (buffer.js:727:11)
    at Writer.addCString (<snipped>\node_modules\pg-protocol\dist\buffer-writer.js:41:30)
    at Object.startup (<snipped>\node_modules\pg-protocol\dist\serializer.js:9:32)
    at Connection.startup (<snipped>\node_modules\pg\lib\connection.js:118:31)
    at Connection.<anonymous> (<snipped>\node_modules\pg\lib\client.js:118:11)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (<snipped>\node_modules\pg\lib\connection.js:49:10)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1127:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

I do not expect that the options property will accomplish anything useful with postgreSQL, but the code is db-independent (and like I said, it worked prior to 8.2.1)

**Comment by charmander** [comment] 2020-08-09 22:43
Duplicate of #2290

**Closed by charmander** 2020-08-09 22:43 UTC

**Comment by charmander** [comment] 2020-08-09 22:46
If you’re seeing this in 8.2.1, that *is* a mistake (it should be only 8.3.0 and later, according to the tags on 06cdf3e9f0a32b84a61e5c8268bce20098a7d1f2), but releasing 8.2.2 to fix that doesn’t seem like it would be too helpful.
