### ISSUE TITLE
How to use "WHERE IN (${array.join(",")})" 

### ISSUE THREAD

**Issue by csulit** [brianc/node-postgres#3064] opened 2023-09-13 06:00 UTC
```
WHERE fram.approver_id IN (${approverIds.join(',')})
```
Error:

```
error: invalid input syntax for type uuid: "dc785ab6-a41c-4460-bf58-ca72fb6b0994,c0edb590-7f9c-41ed-9d3b-6fa6632ef2d9"
```

**Comment by charmander** [comment] 2023-09-13 06:22
Duplicate of #1452

**Closed by charmander** 2023-09-13 06:22 UTC
Labels: question
