### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by olav35** [brianc/node-postgres#2245] opened 2020-06-21 12:19 UTC
The examples on the welcome and connecting sections does not work.

<img width="1128" alt="Skjermbilde 2020-06-21 kl  14 17 38" src="https://user-images.githubusercontent.com/24797093/85224357-298b9280-b3ca-11ea-9415-2cb1f7e18ddf.png">

**Comment by boromisp** [comment] 2020-06-21 15:43
As the error message in the attached screenshot says, the [`await` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) can only be used inside an `async` function.
You need to wrap the code in an async function:
```js
const { Client } = require('pg')
const client = new Client()

(async () => {
  await client.connect()
  const res = await client.query('SELECT $1::text as message', ['Hello world!'])
  console.log(res.rows[0].message) // Hello world!
  await client.end()
})();
```

This isn't the first time this question has made it here (eg. https://github.com/brianc/node-postgres/issues/2228), it is probably worth fixing in the documentation.

**Comment by vitaly-t** [comment] 2020-06-21 16:51
This is the very basics of the asynchronous programming, and shouldn't need explanation here.

**Comment by charmander** [comment] 2020-06-22 12:35
Duplicate of #1631

**Closed by charmander** 2020-06-22 12:35 UTC

**Comment by olav35** [comment] 2020-06-24 18:11
> This is the very basics of asynchronous programming, and shouldn't need explanation here.

What is the benefit of not having working examples?

**Comment by vitaly-t** [comment] 2020-06-24 18:17
@olav35 The example is working perfectly, you are just not using it right. Open `await` works inside MJS files only, it is kind of ABC of asynchronous programming to know that if you not using MJS, you are expected to place `await` calls inside `async`. The examples should not need to explain that, as it is too basic.
