### ISSUE TITLE
error: connection requires a valid client certificate with pg-pool 3.2.2

### ISSUE THREAD

**Issue by eyalcohen** [brianc/node-postgres#2405] opened 2020-11-10 06:23 UTC
With configuration as follows:

```
const postgresConfig = {
  ...
  ssl: {
    rejectUnauthorized: false,
    ca: env.serverca,
    key: env.clientkey,
    cert: env.clientcert
  }
  ...
}
```

I get an `error: connection requires a valid client certificate`

My configuration worked fine with `pg  8.4.1` / `pg-pool 3.2.1` and breaks on `pg 8.4.1` / `pg-pool 3.2.2`.

I believe commit 80c500ffbffff8c2445dce44661e85590dc026e3 is the source of my issue, but perhaps there is a more correct way to pass the certificates now.

**Comment by brianc** [comment] 2020-11-10 17:42
This should be fixed on the version I released today! Please let me know if
its still not working....we have test coverage for this now.

**Comment by charmander** [comment] 2020-11-10 22:53
Duplicate of #2392

**Closed by charmander** 2020-11-10 22:53 UTC

**Comment by domosapien** [comment] 2020-11-13 20:48
This was still broken as of yesterday. It seems like pg-pool@3.2.2 is breaking it. See https://github.com/vitaly-t/pg-promise/issues/764#issuecomment-726828644

**Comment by charmander** [comment] 2020-11-13 23:35
@domosapien Did you upgrade to pg 8.5.1?

**Comment by domosapien** [comment] 2020-11-13 23:41
> @domosapien Did you upgrade to pg 8.5.1?

I have not. Looking at the diff between 8.5.0 and 8.5.1, it doesn't look like anything really would affect what I'm seeing, or what others have reported in that thread. I can attempt that version soon, but I don't have high hopes.

**Comment by charmander** [comment] 2020-11-14 00:16
@domosapien 8.5.0 should be fine. Are you using pg-promise? pg-promise still depends on 8.4.1.

**Comment by domosapien** [comment] 2020-11-15 22:21
@charmander ahh, I guess the changes in 8.5.0 fixes it (tested with a beta version of pg-promise that updates the lib version). I thought it was an issue here too due to pg-pool requiring a set version in the testing we had done. Thanks for the support.
