### ISSUE TITLE
pool.connect() hangs indefinitely

### ISSUE THREAD

**Issue by asipser** [brianc/node-postgres#2282] opened 2020-07-17 00:21 UTC
Currently on one of my computers pool.connect() hangs indefinitely and never runs the callback function inside of it. 

The server code that I run currently looks like:
```  ...
    const connectionString = process.env.POSTGRES_CONNECTION_URI;
    pool = new Pool({connectionString});
    pool.connect((err, client, done) => {
      if (err) logger.error("Error connecting to Postgres", err);
      else logger.info("Server connected to Postgres");
      done(err);
    });
    pool.on("error", function(err) {
      logger.error("Postgres err: ", err);
    });
  },
...
```

Two of my computers print that they connect to my PG database succesfully, while the one which doesn't work simply hangs and prints nothing. I'm not too sure how to debug this, any suggestions?

node version: 14.5.0
pg package version: 7.17.1
computer OS: Mac OSX 10.14.6

**Comment by brianc** [comment] 2020-07-17 00:53
Try upgrading to pg latest (8.x) - pg@7.x doesn't work on node 14
unfortunately

**Comment by charmander** [comment] 2020-07-17 00:59
Duplicate of #2279

**Closed by charmander** 2020-07-17 00:59 UTC

**Comment by JoelIF** [comment] 2021-04-16 03:30
Well, as I missed it I will point out for others. We have to update the pg package not the pg database.
