### ISSUE TITLE
bind message supplies 2 parameters, but prepared statement \"\" requires 1

### ISSUE THREAD

**Issue by DaliborTrampota** [brianc/node-postgres#2816] opened 2022-09-18 11:36 UTC
Hi, I have this piece of code and for some reason it wont replace the $2 with the proper variable

code is varchar(10)
expiryDate is date

let imageID = 'ABCDEFG'
let lifetime = 604800000
await this.pg.query("INSERT INTO media(code, expiryDate) VALUES($1, CURRENT_DATE + INTERVAL '$2 ms')", [imageID, lifetime])

it says it requires only one parameter but I have two in there.

I have to make my query like this 
await this.pg.query(`INSERT INTO media(code, expiryDate) VALUES($1, CURRENT_DATE + INTERVAL '${lifetime} ms')`, [imageID])

**Comment by boromisp** [comment] 2022-09-18 18:01
You can't have a parameter inside an SQL string literal. You have to rewrite you query, a few examples:
https://stackoverflow.com/questions/68805215/how-to-pass-an-interval-parameter-to-a-prepared-statement

**Comment by charmander** [comment] 2022-09-19 17:10
Duplicate of #2737

**Closed by charmander** 2022-09-19 17:10 UTC

**Comment by brianc** [comment] 2022-09-27 10:30
> ... why it cant just replace $x with the variable??

this is a postgres behavior and has nothing to do with node-postgres.  we don't parse/modify your query, we just send it to the backend. postgres itself has strict rules on what can be paramterized.
