### ISSUE TITLE
node version 18 on macos M1  problem with pg connection

### ISSUE THREAD

**Issue by truongbi** [brianc/node-postgres#2970] opened 2023-05-04 07:39 UTC
Does anyone know how to solve the issue when the node version 18 on macos M1 is not working with pg connection?

I tried the below code in macos m1 with node version 18
```
const { Client } = require("pg");

const client = new Client();


(async () => {
  await client.connect();
  const res = await client.query("SELECT $1::text as message", [
    "Hello world!",
  ]);
  console.log(res.rows[0].message); // Hello world!
  await client.end();
})();
```

but the error raised:
```
Error: connect ECONNREFUSED ::1:5432
```

When I tried it with node version 14, it worked perfectly

I used: `pg@8.10.0`, `postgres@15.2` `node@18.16.0` `mac m1 monterey`

**Comment by charmander** [comment] 2023-05-04 07:44
Duplicate of #2895

**Closed by charmander** 2023-05-04 07:44 UTC
