### ISSUE TITLE
yarn berry error: pg-cursor tried to access pg, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by abh1kg** [brianc/node-postgres#2458] opened 2021-01-29 03:21 UTC
Using "pg-cursor" in a project managed by "yarn berry" reports the error: `pg-cursor tried to access pg, but it isn't declared in its dependencies` when used with "strict" mode of dependency management.

**Comment by charmander** [comment] 2021-01-29 23:55
Duplicate of #2249

**Closed by charmander** 2021-01-29 23:55 UTC
