### ISSUE TITLE
exhausting the pool

### ISSUE THREAD

**Issue by kessler** [brianc/node-postgres#517] opened 2014-02-01 16:45 UTC
Hi Brian

To continue our brief communication, here is a code that demonstrates the problem.

The following will exhaust the pool and only two queries will ever be executed (instead of 4), is this normal? am I missing something here?

```
var pg = require('pg')

var connectionString = 'your connection string here'

pg.defaults.poolSize = 2

var executedCount = 0

function query() {
    pg.connect(connectionString, function (err, conn, done) {
        conn.query('select 1+1', function (err, results) {
            console.log(++executedCount)
            done(1) //destroy the connection
        })
    })
}

console.log('dont let the process exit after two queries')
setTimeout(function() {
    console.log('timed out')
}, 10000)

query()
query()
query()
query()
```

**Comment by BeeDi** [comment] 2015-04-16 15:50
I had the same problem, thanks for the tip @kessler ! 

@brianc, since the problem occurs in node-pool, would it be a good idea to change the default value for the minimum number of resources to keep in pool to 1 in your [pg pool code](https://github.com/kessler/node-postgres/blob/master/lib/pool.js#L18) ? 

I reproduced the previous example and a min value of 1 was able to resolve the issue, also the documentation in node-pool says that it's safe to have a value, whatever the max value is set to. 
> if this is set > max, the pool will silently set the min to factory.max - 1

**Comment by FlamingTempura** [comment] 2015-04-23 18:52
Also just had this problem - @kessler 's suggestion solved it.

**Comment by charmander** [comment] 2018-01-03 08:26
Fixed in pg 7.

**Closed by charmander** 2018-01-03 08:26 UTC
Labels: bug
