### ISSUE TITLE
JSON arrays are being converted to PostgreSQL arrays and causing errors

### ISSUE THREAD

**Issue by LJNeon** [brianc/node-postgres#1519] opened 2017-11-22 01:49 UTC
PostgreSQL Version: 9.3 (I can't update this due to the environment I'm using, but it's still a supported version so shouldn't be a problem)
Node.js Version: 9.2.0
pg Version: 7.4.0 (Pure JavaScript Client) 

So I have a JSON column that I want to store arrays in, but whenever I try to update that column with an array it throws
```js
// I cut out most of the error to make it more readable
{ error: invalid input syntax for type json
    at Connection.parseE (/home/ubuntu/workspace/node_modules/pg/lib/connection.js:546:11)
...
  code: '22P02',
  detail: 'Expected ":", but found "}".',
...
  where: 'JSON data, line 1: {"test"}',
...
}
```
Code to reproduce:
```js
pg.Pool.query("UPDATE table_name SET column_name = $1 WHERE id = $2", [["test"], "ROW_ID"]);
```

I believe the problem is that pg is converting the array to a PostgreSQL array instead of a JSON array, which causes the error.

**Comment by charmander** [comment] 2017-11-22 03:28
Pass `JSON.stringify(["test"])` as the parameter. Duplicate of #442

**Comment by charmander** [comment] 2017-11-22 03:29
Duplicate of #442. Pass JSON.stringify(["test"]) as the parameter.

**Comment by charmander** [comment] 2017-11-22 03:29
Duplicate of #442

**Closed by charmander** 2017-11-22 03:28 UTC

**Comment by LJNeon** [comment] 2017-11-22 03:31
I really have to agree with #442, this is something that should be handled by node-postgres, not us manually. The current behavior is extremely unexpected and the fix is unclear.

**Comment by charmander** [comment] 2017-11-22 03:51
Doing that is incompatible with the way pg works right now (determining string representations solely through JavaScript types). It could change to asking for parameter descriptions before serializing query values. @brianc, would you be interested in doing that in a future major version?

**Comment by tux86** [comment] 2024-07-30 08:22
make your column have a type of jsonb[] rather than jsonb.
