### ISSUE TITLE
node-postgres may silently crash the host process

### ISSUE THREAD

**Issue by yushih** [brianc/node-postgres#2691] opened 2022-01-19 18:42 UTC
If `Client.query` is called without calling `Client.connect` first, the process just exits. It's more reasonable to return a rejected promise or event better, automatically call `connect`.

To reproduce the problem, run the script:
```
const { Client } = require('pg');
const client = new Client();

//client.connect();

const result = client.query('Select 1')
  .then(() => {
    console.log('should execute');
    client.end();
  })
  .catch(console.error);
```

The expected behavior is either an error gets output, or 'should execute' is output. Current behavior is the process exits at `client.query`.

**Comment by charmander** [comment] 2022-01-20 07:26
It’s not a crash, it just doesn’t start any operations. Also, if you call `connect` afterwards, the queued query should run.

**Comment by charmander** [comment] 2022-01-20 07:29
Duplicate of 2272

**Closed by charmander** 2022-01-20 07:29 UTC

**Comment by yushih** [comment] 2022-01-20 17:21
This is crash. If "it just doesn't start any operation", otherwise the `finally` clause  should execute:
```
```

**Comment by yushih** [comment] 2022-01-20 17:28
Thanks!
