### ISSUE TITLE
pg version not compatible with NodeJS14?

### ISSUE THREAD

**Issue by Garfield2013** [brianc/node-postgres#2202] opened 2020-05-07 16:25 UTC
I just updated NodeJS to version 14.0 or 14.2 but then pg suddenly get stuck when trying to `execute:  

pool.connect(function(error, client, done)){...}`

I really like to use NodeJS version 14.0 - it is not supported by pg?

**Comment by charmander** [comment] 2020-05-07 17:45
Duplicate of #2180

Upgrade to pg 8.0.3.

**Closed by charmander** 2020-05-07 17:45 UTC
