### ISSUE TITLE
Docs are wrong or functions are not async

### ISSUE THREAD

**Issue by kevinmccarthy** [brianc/node-postgres#1631] opened 2018-04-30 23:30 UTC
Running the example code on Node 8.10 does not work. Vanilla Ubuntu with default node.js.

```
#!/usr/bin/env node
let { Client } = require('pg')
const client = new Client()
await client.connect()
const res = await client.query('SELECT $1::text as message', ['Hello world!'])
console.log(res.rows[0].message) // Hello world!
await client.end()
```

returns this:
```
kevin@node:~$ ./zz
/home/kevin/zz:4
await client.connect()
^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by charmander** [comment] 2018-04-30 23:49
Duplicate of #1629

**Closed by charmander** 2018-04-30 23:49 UTC

**Comment by ktats** [comment] 2020-06-10 23:51
Can we reopen this?

**Comment by charmander** [comment] 2020-06-11 00:19
@ktats It’s covered by the duplicate #1629, which is open, so there’s no need to.
