### ISSUE TITLE
Insert or update with an empty Array creates Object in a JSON field

### ISSUE THREAD

**Issue by yanickrochon** [brianc/node-postgres#864] opened 2015-09-24 19:46 UTC
A query like 

```
var q = adapter.query('INSERT INTO tbl_data (id, data) VALUES ($1, $2)', [1, [] ]);
```

will act _exactly_ the same as

```
var q = adapter.query('INSERT INTO tbl_data (id, data) VALUES ($1, $2)', [1, {} ]);
```

Because an object will be inserted into the column instead of an array. Which is bad as the subsequent SELECT, fetching the data, needs to perform unnecessary conversions.

When I navigate to `tbl_data`, and manually change the column's value from `{}` to `[]`, then the subsequent SELECT retrieves the correct information.

**Comment by whoeverest** [comment] 2016-03-04 14:33
I'm having the same problem. I'll try to find and fix the issue, then submit a RP.

**Comment by charmander** [comment] 2017-08-06 06:55
Duplicate of #442. Use JSON.stringify on the parameter you’d like to pass as JSON.

**Closed by charmander** 2017-08-06 06:55 UTC
