### ISSUE TITLE
How can I set default schema / seatch path while configuring the client?

### ISSUE THREAD

**Issue by IdanDavidi** [brianc/node-postgres#1421] opened 2017-08-20 20:47 UTC
I am configuring the client using the object constructs:

```javascript
        let clientConfig:ClientConfig = {
            host : "myhost",
            password : "mypass",
            port : 5432,
            user : "my-user",
            database : "my-db",
            ssl : true
        };

        this._client = new Client(clientConfig);
```

How can I tell it what is the default schema so I do not have to specify it in the every query?

thanks.

@liorhirsch

**Comment by charmander** [comment] 2017-08-21 02:43
Duplicate of #1123

**Closed by charmander** 2017-08-21 02:43 UTC
