### ISSUE TITLE
Website / documentation issue -- can't scroll TOC

### ISSUE THREAD

**Issue by edqallen** [brianc/node-postgres#1809] opened 2019-01-10 19:44 UTC
The left-hand side TOC on the project website @ https://node-postgres.com/ cannot be scrolled.  If the window is not tall enough to show all entries, they cannot be navigated to.  Tested in Chrome 71 and Edge 44.

**Comment by charmander** [comment] 2019-01-11 04:58
Duplicate of #1467

**Closed by charmander** 2019-01-11 04:58 UTC
