### ISSUE TITLE
debug the query statement

### ISSUE THREAD

**Issue by its-dibo** [brianc/node-postgres#3080] opened 2023-10-17 11:55 UTC
how to debug the final statement just before sending it to the database, like that:
```
query(`insert into mytable values($1)`, ["test's"])
```
I want to see the final statement i.e. `insert into mytable values('test\'s')`

**Comment by boromisp** [comment] 2023-10-17 12:16
This library does not substitute the query parameters, it will forward the query string and the individual positional arguments as is.

If the postgres server logs the query for some reason, it will look something like this:

```
LOG:  bind <unnamed>: insert into mytable values($1)
DETAIL:  parameters: $1 = 'test''s'
```

**Comment by charmander** [comment] 2023-10-18 23:39
Duplicate of #1309

**Closed by charmander** 2023-10-18 23:39 UTC
Labels: question
