### ISSUE TITLE
Callback issue with dbClient.query

### ISSUE THREAD

**Issue by natejstar** [brianc/node-postgres#900] opened 2015-12-04 00:27 UTC
I'm looking for a little help with my code structure as it pertains to my queries.

Let's say I have a function called access_db as follows:

function access_db(callback) {
    pg.connect(conString, function(err, dbClient, done) {
        if(err) return console.error("db error", err);
        dbClient.query('Select * from X',function(err, result) {
            if(err) return console.error("db error", err);
            name = result.rows[0].name;
            done();
            callback(name);
        });
    }
}

I made up the variable name, but I don't have an issue with getting the proper content.
So assuming this function is in a module called db, I do the following:
db.access_db(function(name) {
    // do something with the name value
})

This generally works fine as well, so that I have the proper values when the callback from the database is triggered. However, my problem is that sometimes (but not always), the code that reads "// do something with the name value" happens twice. So I tested not doing the dbClient.query portion of the database function, which fixes the issue. But when I do the query, somehow the callback that uses the name value happens twice.

Any thoughts? Thanks!

**Comment by zsck** [comment] 2015-12-16 15:16
May I suggest wrapping your code to make it formatted and syntax highlighted? It's hard to read your sample code as it stands.
See [the Github-flavoured Markdown docs](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting)

**Comment by natejstar** [comment] 2015-12-16 16:42
```
function access_db(callback) {
pg.connect(conString, function(err, dbClient, done) {
if(err) return console.error("db error", err);
dbClient.query('Select * from X',function(err, result) {
if(err) return console.error("db error", err);
name = result.rows[0].name;
done();
callback(name);
});
}
}
```

**Comment by zsck** [comment] 2015-12-16 22:27
Just as a thought, does the problem persist if you write `access_db` like so?

```js
function access_db(callback) {
  pg.connect(conString, function (err, dbClient, done) {
    if (err) {
      callback(err, null);
    } else {
      dbClient.qury('select * from X limit 1', function (err, result) {
        if (err) {
          callback(err, null);
        } else {
          var name = result.rows[0].name;
          done();
          callback(null, name);
        }
      });
    }
  });
}

db.access_db(function (err, name) {
  if (err) {
    console.error('DB Error', err);
  } else {
    // Do something with the name value
  }
});
```

**Comment by natejstar** [comment] 2015-12-20 00:13
@zsck thanks for the suggestion! Unfortunately those changes didn't seem to fix the problem. I do not seem to be hitting error cases because I'm putting logs in them as well and I never see those in the cases where I do have the duplicates. So strange I can't imagine why it seems to fork off sometimes.

**Comment by natejstar** [comment] 2015-12-31 21:23
As an update, I'm still having trouble with this. Any suggestions?

**Comment by brianc** [comment] 2015-12-31 21:27
I really don't know what it could be without seeing more of the code around it.  I can almost guarantee this library itself isn't calling your callback more than once...we've been running lots of prod sites for a long time & would have seen a lot more stuff like that.  That makes me think there's a 99% likelihood the issue is in the surrounding code or how you're calling things.  Debugging issues like this in node can be a challenge due to the everything async & I feel your pain, but I don't think I'm gonna be able to help you out much unless you can give me a self-contained piece of reproducible code here that demonstrates there's an issue with pg itself.

**Comment by joskuijpers** [comment] 2016-06-20 15:36
@natejstar Still having this problem? Could you give more information?

**Comment by natejstar** [comment] 2016-06-20 16:02
Hi Jos,

Thank you for reaching out! I am all set, this was an error I personally
had. I apologize I forgot to close the issue off.

Thanks,
Nate

On Mon, Jun 20, 2016 at 9:36 AM, Jos Kuijpers <notifications@github.com>
wrote:

> @natejstar <https://github.com/natejstar> Still having this problem?
> Could you give more information?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/brianc/node-postgres/issues/900#issuecomment-227179199>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AM8vvRVaG8BoJDENLVUK6fvWmtw0WkVSks5qNrOCgaJpZM4GufYU>
> .
>



-- 
*Nate Jones*   \\  nate@jstar.ai
Software Developer \\  607.425.4241

<http://josh.ai>

**Comment by joskuijpers** [comment] 2016-06-20 16:35
@brianc You can close this one

**Comment by brianc** [comment] 2016-06-21 14:43
💃

**Closed by brianc** 2016-06-21 14:43 UTC
