### ISSUE TITLE
Not able to insert array of json object into Postgres DB via query in Express

### ISSUE THREAD

**Issue by thesolotraveller** [brianc/node-postgres#1383] opened 2017-07-21 08:02 UTC
Hello,
I can do the required in PgAdmin but while querying in the app I am building, things are not working. Here is the error it shows up.

error: invalid input syntax for type json
name: 'error',
  length: 199,
  severity: 'ERROR',
  code: '22P02',
  detail: 'Expected ":", but found "}".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: ...:\\"Angry\\",\\"speaker\\":\\"Teletext Callperson\\"}"}',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'json.c',
  line: '1198',
  routine: 'report_parse_error' }

Any sort of help in de-bugging this is appreciated. Thanks.

**Comment by charmander** [comment] 2017-07-21 08:14
Duplicate of #442. Use `JSON.stringify` on the parameter you’d like to pass as JSON.

**Closed by charmander** 2017-07-21 08:14 UTC

**Comment by thesolotraveller** [comment] 2017-07-21 08:56
The objects in array are data rich and JSON.stringify is converting floats to strings as well.
Also UPDATE query got passed but didn't update the database. Here is result I got on console - 

Result {
  command: 'UPDATE',
  rowCount: 0,
  oid: NaN,
  rows: [],
  fields: [],
  _parsers: [],
  RowCtor: null,
  rowAsArray: false,
  _getTypeParser: [Function: bound ] }

Any suggestions ?

**Comment by charmander** [comment] 2017-07-21 09:35
How do you know it didn’t update the database? Please show a complete example (script, schema, expected results, actual results).

**Comment by thesolotraveller** [comment] 2017-07-21 10:11
Simply I checked in pgAdmin. Data is not altered at all.
Here is my script - 
        client.query('UPDATE audio_files SET alias_name_of_column=$1 where alias_name_of_other_column=$2', [json, url], function(err, result) {
            if (err) {
                console.log(err);
            } else {
                console.log(result);
            }
        });
I should get a result where row array is not empty and of size just 1 (this is fixed) .... containing the updated one .... and data should get updated .... but it is not

**Comment by charmander** [comment] 2017-07-21 10:22
`rowCount` was `0`, so presumably nothing matched the `WHERE` clause. Log the value of `url` and ensure that it matches some row.

**Comment by thesolotraveller** [comment] 2017-07-21 10:29
Thanks a lot. I was not paying attention to that thing. It worked.
