### ISSUE TITLE
INSERT INTO request does not execute without any error and blocks the execution

### ISSUE THREAD

**Issue by Flydexo** [brianc/node-postgres#2785] opened 2022-08-18 17:13 UTC
I have a nestjs server which needs to edit data in my db but on specific tables the query does not execute and the execution is blocked until I get a pg timeout error

**Comment by Flydexo** [comment] 2022-08-18 17:41
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/app/node_modules/.pnpm/pg@8.7.3/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:509:28)
    at Connection.emit (node:events:390:28)
    at Socket.<anonymous> (/app/node_modules/.pnpm/pg@8.7.3/node_modules/pg/lib/connection.js:107:12)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (/app/node_modules/.pnpm/pg@8.7.3/node_modules/pg/lib/client.js:319:10)
    at Connection.<anonymous> (/app/node_modules/.pnpm/pg@8.7.3/node_modules/pg/lib/client.js:149:16)
    at Object.onceWrapper (node:events:509:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by brianc** [comment] 2022-08-23 16:39
I'm going to close this as it's 99% likely a bug in your code & not the library.  If you can submit a code example that reproduces the issue and is self-contained we can take a look, but since its working in some parts of your app and not others that points pretty strongly towards it being an application code level bug.

**Closed by brianc** 2022-08-23 16:39 UTC
Labels: waiting for more info
