### ISSUE TITLE
Critical Issue with Numeric/Decimal Type

### ISSUE THREAD

**Issue by Letsion** [brianc/node-postgres#2818] opened 2022-09-21 09:39 UTC
Hello,
I use for balance and prices numeric respectively in SQL decimal.
When I SELECT one table, it gets me for numeric/decimal a string and not a number/float.

Postgres Version: 13.4
Node Version: v16.15.1

Postgres Structure:
```
Table "public.transactions"
      Column       |            Type             | Collation | Nullable |                 Default
-------------------+-----------------------------+-----------+----------+------------------------------------------
 id                | integer                     |           | not null | nextval('transactions_id_seq'::regclass)
 userId            | integer                     |           | not null |
 drinkId           | integer                     |           | not null |
 drinkName         | character varying(255)      |           | not null |
 amount            | integer                     |           | not null |
 oldSaldo          | numeric                     |           | not null |
 saldo             | numeric                     |           | not null |
 pricePerDrink     | numeric                     |           | not null |
 isStorno          | boolean                     |           | not null |
 stornoTransaction | boolean                     |           | not null |
 createdAt         | timestamp without time zone |           | not null |
Indexes:
    "transactions_pkey" PRIMARY KEY, btree (id)
```
Example:

```ts
await tableCreation.query(
            `CREATE TABLE transactions (id SERIAL PRIMARY KEY, "userId" integer NOT NULL, "drinkId" integer NOT NULL, "drinkName" VARCHAR(255) NOT NULL, amount integer NOT NULL, "oldSaldo" decimal NOT NULL, saldo decimal NOT NULL, "pricePerDrink" decimal NOT NULL, "isStorno" boolean NOT NULL, "stornoTransaction" boolean NOT NULL, "createdAt" timestamp NOT NULL)`
        );
```

```ts
const transactions = await client.query(`SELECT * FROM transactions WHERE id = $1`, [transactionId]);
const transaction = transactions.rows[0] as Transaction;
console.log(transaction);
```

Console Output:
```js
{
  id: 1,
  userId: 40,
  drinkId: 5,
  drinkName: 'Abens. Spritzig',
  amount: 4,
  oldSaldo: '-0.9',
  saldo: '-2.7',
  pricePerDrink: '0.45',
  isStorno: false,
  stornoTransaction: false,
  createdAt: 2022-09-21T08:50:23.375Z
}
```

**Comment by charmander** [comment] 2022-09-22 04:05
JavaScript strings can represent everything `numeric` can precisely; JavaScript numbers cannot. This default avoids silently rounding/corrupting your data. It’s not very hard to convert a string to a number if that’s what you want.

**Comment by charmander** [comment] 2022-09-22 04:05
Duplicate of #811

**Closed by charmander** 2022-09-22 04:05 UTC
