### ISSUE TITLE
process stalled when selecting large amount of data

### ISSUE THREAD

**Issue by rpedela** [brianc/node-postgres#526] opened 2014-02-22 21:58 UTC
This is only for the native version. When selecting 100s of MB (in my case), the process stalls reading all the returned data even in single row mode. In the pure JS case, I have verified the read task yields back to the main loop periodically by printing a message every 100 ms. However this message is not printed when using the native version until SELECT finishes.

I don't think it has anything to do with the size of the returned data, I just noticed because of such a large read. My hypothesis is that the C++ driver is not properly yielding back to the main loop between reads. Another option is that single row mode is not implemented properly or there is a problem with libpq (hard to imagine).

VERSIONS
ubuntu: 12.04 LTS
postgres: 9.3.1
node.js: 0.10.17
node-postgres: 2.11.1

```
setInterval(
    function() {
        console.log('loop alive');
    },
    100
);

...

var query = client.query('SELECT * FROM my_large_table');

query.on('row', function(row) {
    console.log(row);
});

query.on('error', function(err) {
    console.log(err);
});

query.on('end', function() {
    console.log('end');
});

```

**Comment by brianc** [comment] 2017-06-16 21:54
Hey @rpedela - there were some recent changes to how we were reading buffers in node that should help w/ very large row results.  Did this happen to you using the native driver or the pure javascript driver?  Closing this since the issue is 3 years old, but feel free to re-open if you're still having the issue.

**Closed by brianc** 2017-06-16 21:54 UTC
