### ISSUE TITLE
ALTER TYPE for enum syntax error for parameter substitution

### ISSUE THREAD

**Issue by krishchow** [brianc/node-postgres#2259] opened 2020-06-28 10:02 UTC
Node: v13.11.0
Postgres Server: 9.5.21

Snippet:
Schema -
`
CREATE TYPE skilltype AS ENUM ('First', 'Second' );
`
Node -
`
let typename="Third";
pool.query('ALTER TYPE skilltype ADD VALUE $1;',[typename])
`

The expected behaviour would be for the typename to be parameterized appropriately, however, the parameterization fails for this query (with error: `error: syntax error at or near "$1"`)

**Comment by vitaly-t** [comment] 2020-06-28 18:06
PostgreSQL doesn't support dynamic enum values, the same way it doesn't support dynamic table names, etc.

If you want everything dynamic to be supported, you would need to use a library that implements its own query formatting, like [pg-promise]. This library however doesn't do its own query formatting, it only sends variables into the server, to be formatted there.

[pg-promise]:https://github.com/vitaly-t/pg-promise

**Comment by charmander** [comment] 2020-06-28 18:40
https://www.npmjs.com/package/pg-format can format literals (with `%L`) into queries that don’t support parameterization.

**Comment by charmander** [comment] 2020-06-28 18:42
Duplicate of #539

**Closed by charmander** 2020-06-28 18:42 UTC
