### ISSUE TITLE
Infinite loop when connecting to non-postgresql server

### ISSUE THREAD

**Issue by MrCheater** [brianc/node-postgres#2099] opened 2020-02-07 09:39 UTC
![tcp](https://user-images.githubusercontent.com/5055654/74017462-599b4180-49a5-11ea-95b4-01a9a8010d74.jpg)

[tcp.pcapng.zip](https://github.com/brianc/node-postgres/files/4169954/tcp.pcapng.zip) <- Wireshark dump

```js
  console.log('Connect started')
  try {

    const connection = new Postgres({ /* credentials */ })
    await connection.connect()
    // Hangs out here forever and 100% CPU

    console.log('Connect finished')

  } catch(error) {
    console.log('Connect failed', error)

    throw error
  }
```
![tcp-2](https://user-images.githubusercontent.com/5055654/74018342-ca8f2900-49a6-11ea-918e-3454d5334dce.jpg)

**Comment by charmander** [comment] 2020-02-07 19:59
Duplicate of #1694

**Closed by charmander** 2020-02-07 19:59 UTC
