### ISSUE TITLE
Syntax error while creating schema

### ISSUE THREAD

**Issue by feyzullahyildiz** [brianc/node-postgres#1798] opened 2018-12-31 13:53 UTC
- pg: 7.7.1
- node: 10.14.1
- os: windows 10
- yarn: 1.10.1 (with yarn workspaces)

```js
adminClient.connect(async (error) => {
    if (error) {
        console.log('db connection error!')
    } else {
        console.log('db_client connected')
        adminClient.query('CREATE SCHEMA $1', ['foobar'])
    }
})
```

Here is the console.

db_client connected
(node:4812) UnhandledPromiseRejectionWarning: error: syntax error at or near "$1"
    at Connection.parseE (C:\Users\Feyzullah\Desktop\Projeler\KGM\Backend\node_modules\pg\lib\connection.js:554:11)    at Connection.parseMessage (C:\Users\Feyzullah\Desktop\Projeler\KGM\Backend\node_modules\pg\lib\connection.js:379:19)
    at Socket.<anonymous> (C:\Users\Feyzullah\Desktop\Projeler\KGM\Backend\node_modules\pg\lib\connection.js:119:22)    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:4812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sehrope** [comment] 2019-01-06 21:45
Parameters cannot be used for identifiers. The identifier has to be part of the SQL text itself.

Use something like pg-format (https://www.npmjs.com/package/pg-format) to quote the value as an identifier and build the entire command string:

```js
const format = require('pg-format');

async function stuff(name) {
    const sql = format('CREATE SCHEMA %I', name);
    await adminClient.query(sql);
}
```

**Comment by charmander** [comment] 2019-01-07 07:17
Duplicate of #539

**Closed by charmander** 2019-01-07 07:17 UTC
