### ISSUE TITLE
Unhandled error when trying to access another database port

### ISSUE THREAD

**Issue by daviialvesjr** [brianc/node-postgres#2474] opened 2021-02-18 15:15 UTC
I tried to access a MySQL port by mistake and it caused my application to crash even with the `.connect()` command inside a `try/catch` block.

![image](https://user-images.githubusercontent.com/13908434/108377076-6a021100-71e2-11eb-9cf5-4df80e8a1da2.png)

Edit: It's not a problem for me right now, I'm just reporting.

**Comment by charmander** [comment] 2021-02-19 01:02
Duplicate of #1940

**Closed by charmander** 2021-02-19 01:02 UTC
