### ISSUE TITLE
Node version 14 exists without error on pool.query 

### ISSUE THREAD

**Issue by dnc-scg** [brianc/node-postgres#2226] opened 2020-05-22 08:12 UTC
```
const { Pool } = require('pg')
    const pool = new Pool({
        ssl: {
            rejectUnauthorized: false,
        }
    })
const na = await pool.query( "text " ).then( .. ).catch( .. )
console.log(' this line never prints ')
```
On node version 14, the process exits without printing any connection error(s), but on node 12 it works as expected.

**Comment by dnc-scg** [comment] 2020-05-23 16:27
pg version 7.18.2

I wondered if it is related to the nodejs issue https://github.com/nodejs/node/issues/22088 which could imply that pg creates a promise, but never calls the resolve or reject on it.

**Comment by charmander** [comment] 2020-05-23 16:40
pg ≤ 8.2.0 doesn’t support Node 14. Please upgrade to pg 8.2.1.

**Comment by charmander** [comment] 2020-05-23 16:41
Duplicate of #2181

**Closed by charmander** 2020-05-23 16:41 UTC

**Comment by dnc-scg** [comment] 2020-05-25 13:46
Thank you :)
