### ISSUE TITLE
False positive DeprecationWarning when using pg with newrelic

### ISSUE THREAD

**Issue by colbyy** [brianc/node-postgres#1348] opened 2017-06-27 15:02 UTC
When requiring the newrelic module in my node app, I get the following DeprecationWarning whenever I do a query with node-postgres:

> (node:62538) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading

I think newrelic adds on some even emitters somewhere and node-postgres warns me that I am adding event emitters to my queries.

I am using a Pool and doing simple queries and treating them like promises. For example:
```js
const getUser = email =>
  db.query('SELECT * FROM users.user WHERE email=$1', [email])
  .then(result => _.get(result, 'rows[0]'));

//db
module.exports = {
  query: (text, params) => pool.query(text, params),
};
```

**Comment by sibedge** [comment] 2017-06-27 15:19
Duplicate of #1332 

Fixed since version 6.3.1

**Comment by colbyy** [comment] 2017-06-27 15:44
I updated to 6.4.0 but I am getting the same issue

**Comment by sibedge** [comment] 2017-06-27 16:45
By any chance you are using a package like `newrelic`? Because that would explain it.

**Comment by colbyy** [comment] 2017-06-27 17:11
yeah I'm using the newrelic package and its a false positive warning from node-postgres

**Comment by sibedge** [comment] 2017-06-27 17:31
Package `newrelic` hacks into packages through events. And as this driver considers query events a deprecated approach, you are getting the warnings.

So it is not this driver's problem, and not so much of the `newrelic`'s, but of both. And there can be no solution to this, unless you can somehow configure `newrelic` not to hack into `pg` via events, which I wouldn't know, as I don't use `newrelic`.

**Comment by charmander** [comment] 2017-06-27 22:19
You can safely ignore this deprecation warning since it doesn’t apply to you and report a bug in newrelic.

**Closed by charmander** 2017-06-27 22:19 UTC
