### ISSUE TITLE
Type parsers conflict

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-postgres#2363] opened 2020-10-07 07:58 UTC
When your application uses multiple third-party modules, each initialized from reusable `Pool`, is there any provision as to how to deal with each module trying to set its own type parsers?

From what I see, we are getting nothing but conflicts in this scenario, as parsers are set on a singleton. Is there any solution to this that I'm not aware of?

**Comment by charmander** [comment] 2020-10-07 23:53
Pass `types` into the constructor. [Option documented](https://node-postgres.com/api/client/#constructor), [value needs documentation](https://node-postgres.com/api/types/).

**Comment by charmander** [comment] 2020-10-07 23:53
Duplicate of #1838

**Closed by charmander** 2020-10-07 23:53 UTC

**Comment by vitaly-t** [comment] 2020-10-08 03:21
Type `TypeOverrides`  appears to be highly reusable. How come it is not exposed by the library's root? It really should be.
