### ISSUE TITLE
Endless loop when connect to a mysql server

### ISSUE THREAD

**Issue by RogerKang** [brianc/node-postgres#1694] opened 2018-07-20 07:44 UTC
## Intro
When I incidentally used pg to connect to a **mysql** database (5.7.17), the node process fell into an **endless loop**.
And I test some another versions of mysql:

* 5.5.43: node process crash due to uncaughtException
* 5.7.17: dead cycle
* 5.7.18: dead cycle
* 5.7.22: node process crash due to uncaughtException

Then I digged into postgres source code.</br>

The cause is that:
### pg do not check the packets sent by server side, so when the server side is not a postgres database, the pg client can not process the packet properly, which will cause unexpected situation including falling into an endless loop or uncauthtException

In my case, this root cause is the first packet from mysql database (5.7.18-log) is:

```
'N\u0000\u0000\u0000\n5.7.18-log\u0000(\u0010\u0000\u0000\u0013n&L\u001f/1K\u0000��!\u0002\u0000��\u0015\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000Z\rbmtsO0\u001evJ\u0000mysql_native_password\u0000'
```

and it will be passed the parseCString function (https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L647) which expect the buffer will contains `0`, but the packet from mysql does not, so parseCString whill do nothing:

```
Connection.prototype.parseCString = function (buffer) {
  var start = this.offset
  var end = buffer.indexOf(0, start)  // if buf do not contain 0, parseCString whill fail to process this packet
  this.offset = end + 1
  return buffer.toString(this.encoding, start, end)
}
```
then node process will fall into the dead loop(https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L118):

```
    while (packet) {
      var msg = self.parseMessage(packet) 
      if (self._emitMessage) {
        self.emit('message', msg)
      }
      self.emit(msg.name, msg)
      packet = self._reader.read()
    }
```

Below is a simple demo to reproduce this issue:

```
//tcp server:

let net = require('net');
let server = new net.Server({
  allowHalfOpen: true
});

server.listen(9001, function (event) {
  console.log('>>>>>> listen on 9001')
})

server.on('connection', (conn) => {
  console.log('connected');
  conn.on('end', () => {
    console.log('Send FIN to client');
    //conn.end();
  })

  conn.write(message, () => {
    console.log('sent message');
  });
});

server.on('end', (conn) => {
  console.log('end', conn);
});

// the packet sent by mysql server (5.7.18-log)
var message = Buffer.from([
  78,0,0,0,10,53,46,55,46,49,56,45,108,111,103,
  0,40,16,0,0,19,110,38,76,31,47,49,75,0,255,247,
  33,2,0,255,129,21,0,0,0,0,0,0,0,0,0,0,90,13,98,
  109,116,127,115,79,48,30,118,74,0,109,121,115,113,
  108,95,110,97,116,105,118,101,95,112,97,115,115,119,111,114,100,0]); 
```

```
// client
var pg = require('pg');
let Client = pg.Client;


var max = 10000;

let config = {
  host: '127.0.0.1',
  port: 9001,
  user: 'root',
  database: 'mysql',
  password: 'password',
  max: 1
}
const client = new Client(config);
client.connect(() => {console.log('connected')})
```
Then client node process will fall into dead loop.

If we change the messgae sent by the server to:

```
// the packet sent by mysql server (5.5.43)
var message = Buffer.from(  [95,0,0,0,10,53,46,53,46,52,51,45,48,117,98,117,
    110,116,117,48,46,49,52,46,48,52,46,49,45,108,
    111,103,0,115,5,0,0,61,58,75,73,108,102,58,48,
    0,255,247,8,2,0,15,128,21,0,0,0,0,0,0,0,0,0,0,
    125,74,54,112,84,51,64,43,81,57,102,121,0,109,
    121,115,113,108,95,110,97,116,105,118,101,95,112,97,115,115,119,111,114,100,0]); 
```

Node process will crash by an uncaughtException:

```
TypeError: Cannot read property 'name' of undefined
	at Socket.<anonymous> (pg@7.4.3@pg/lib/connection.js:138:21)
```

## Summary
The simplest way to avoid this issue to to **ensure the server side is a valid postgres server**. </br>
But in my cases, sometime I cannot predict wheather the server is a postgres server.</br>
I think is is necessary for pg client to be robust enought to avoid crashing by server side.</br>
So pg client should check the packets sent by server to ensure it is a postgres server, **at least in the very early stage of the connection, which can avoid most of risks**.

**Comment by vitaly-t** [comment] 2018-07-20 22:50
This one is funny, and very-very unique, so would be of tiny-tiny priority of 100th.

Unless you find the cause and submit a PR yourself, I wouldn't expect anyone else to spend time on it.

**Comment by charmander** [comment] 2018-07-21 00:37
Duplicate of #1048

**Closed by charmander** 2018-07-21 00:37 UTC

**Comment by MrCheater** [comment] 2020-02-10 08:18
+1
