### ISSUE TITLE
Verbose Error not shown correctly in pg.native

### ISSUE THREAD

**Issue by xfumihiro** [brianc/node-postgres#982] opened 2016-04-07 19:24 UTC
The error incorrectly shown in pg.native:

**{ [Error: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (70911911911911911, null, sdf, null, null, null, null, null, 2016-04-07 19:10:29, 2016-04-07 19:10:29, f, 0, 0, 0).
]
  severity: 'ERROR',
  sqlState: '23502',
  messagePrimary: 'null value in column "id" violates not-null constraint',
  messageDetail: 'Failing row contains (70911911911911911, null, sdf, null, null, null, null, null, 2016-04-07 19:10:29, 2016-04-07 19:10:29, f, 0, 0, 0).',
  sourceFile: 'execMain.c',
  sourceLine: '1636',
  sourceFunction: 'ExecConstraints' }**

which should be shown as:

**{ [error: null value in column "id" violates not-null constraint]
  name: 'error',
  length: 282,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (70911911911911911, null, sdf, null, null, null, null, null, 2016-04-07 19:11:36, 2016-04-07 19:11:36, f, 0, 0, 0).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'user',
  column: 'id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1636',
  routine: 'ExecConstraints' }**

**Comment by vitaly-t** [comment] 2016-04-07 20:22
Duplicate of #938  + #972.

**Closed** 2016-04-08 03:25 UTC
