### ISSUE TITLE
Node V6 Incompatibility?

### ISSUE THREAD

**Issue by StretchKids** [brianc/node-postgres#1029] opened 2016-05-24 00:03 UTC
I tried building our environment with Node V6.2. We had been using Node V5.7 but since have tested with Node V5.9.1. The app has been developed under Windows 10 and deployed under Ubuntu 15.10 moving to 16.04 LTS.

Under Node V6 we hit 3 problems:

1) Postgres 9.4 and 9.5.3 returned password authentication failure
2) PM2  1.0.2 would not return after starting a process
3) When trying to debug under Webstorm 16.1.2 on Windows, the it failed with a "ReferenceError: v8debug is not defined".

All the problems disappeared when reverting to Node v5.9.1

The Webstorm problem is still outstanding with a workaround  adding --expose-debug-as=v8debug  to "Node parameters" buried on their issues database.

PM2 has a fix in 1.1.3 (not in Ubuntu package repository at this time) labeled "node v6 compat" that consists of removing a call to **hasOwnProperty** in a wrapper around a cloning function.

Is this a known node-postgres to Node v6 compatibility issue?

**Comment by vitaly-t** [comment] 2016-05-24 01:11
Please research before opening issues. This has been duplicated so many times by now.

* https://github.com/brianc/node-postgres/issues/1000
* https://github.com/brianc/node-postgres/issues/1019
* https://github.com/brianc/node-postgres/issues/1003

**Comment by brianc** [comment] 2016-05-24 01:26
Sorry for the issue @stretchKids - can you provide a code sample that works
on node v5 but does not work on node v6? This is high on my list to look
at.

**Comment by apkoponen** [comment] 2016-05-25 09:24
I had a similar issue when upgrading from node 5.x to 6.x and was able to fix it just by deleting node_modules folder, running npm install and redeploying the app.

**Comment by BornaP** [comment] 2016-05-25 11:48
@apkoponen : In short you have just updated to newer release where bug has been solved :)

I can confirm that I've experienced the same issue before pulling 6fddc566f09cf6b5919638a6f69c251e20437b75 that resolves it.

**Comment by apkoponen** [comment] 2016-05-25 16:55
Yup.

**Comment by LinusU** [comment] 2016-06-09 16:34
I hade this problem as well, but it was solved by updating to version 5.0.0.

> Postgres 9.4 and 9.5.3 returned password authentication failure

**Comment by jtiscione** [comment] 2016-06-15 18:50
I have this "v8debug is not defined" problem with 6.2.0, but reinstalling the node modules didn't help.

**Comment by brianc** [comment] 2016-06-15 22:46
I have installed node-postgres on node v6 and v5 a whole bunch - never had any issues. I think it's something w/ your environment. Have you tried deleting `node_modules`?

**Comment by jtiscione** [comment] 2016-06-16 03:38
I figured it out- the correct node option to use (on node 6.2.0) is:
`--expose-debug-as=v8debug`

**Comment by brianc** [comment] 2016-06-16 03:40
Weird - I don't have to do that. I just have 6.2 and i do `npm i pg` and it
"just works" - are you doing something fancy w/ pg that would require
exposing dbug?

**Comment by jtiscione** [comment] 2016-06-16 03:59
Whoops- I didn't see the part of the original post where he mentions his Webstorm problem being fixed by "--expose-debug-as=v8debug". Since I'm also using Webstorm I figure it must be a bug on their end.
(The problems with Postgres and PM2 look like a separate issue.)

**Comment by jbcpollak** [comment] 2016-06-22 03:28
Just randomly came across this bug looking for something else. Just to clarify - the v8debug issue is related to WebStorm and has nothing to do with `pg`. The next patch release of WebStorm will fix that problem.

**Comment by brianc** [comment] 2016-06-22 03:30
Ah thanks for the update from both @jtiscione and @jbcpollak!  Really appreciate y'all diving in on things like this that are slightly outside of the wheelhouse of the lib in general but still impact the community!

**Closed by brianc** 2016-06-22 03:30 UTC
