### ISSUE TITLE
Native spews out NOTICE when `CREATE TABLE IF NOT EXISTS` does not create table that already exists

### ISSUE THREAD

**Issue by OJezu** [brianc/node-postgres#737] opened 2015-02-26 11:53 UTC
The following notice:
`NOTICE:  relation "some_table" already exists, skipping`
Is not `console.log`ged when using non-native pq, but is outputted with native.

**Comment by brianc** [comment] 2017-06-16 22:10
Closing as duplicate of https://github.com/brianc/node-postgres/issues/752

**Closed by brianc** 2017-06-16 22:10 UTC
