### ISSUE TITLE
How to insert multi target columns ?

### ISSUE THREAD

**Issue by Shekhrozx** [brianc/node-postgres#1641] opened 2018-05-09 07:03 UTC
I would like to add `n` number of items all with a single insert query.
`INSERT INTO foo(a,b) VALUES (q,r), (s,t) ...`
How can I do this?

**Comment by charmander** [comment] 2018-05-09 07:18
Duplicate of #957

**Comment by charmander** [comment] 2018-05-09 07:19
See https://github.com/brianc/node-postgres/issues/957#issuecomment-295583050 / https://github.com/brianc/node-postgres/issues/1116#issuecomment-283854402

**Closed by charmander** 2018-05-09 07:18 UTC
Labels: question
