### ISSUE TITLE
COUNT() results are returned as strings

### ISSUE THREAD

**Issue by rlindner81** [brianc/node-postgres#1618] opened 2018-04-14 09:29 UTC
IMO they should be returned as Numbers.

Using Strings is counter-intuitive, because the result will always be an integer and other fields are returned with their closest matching JS type. I ran into this, because Strings behave differently when sorting on these fields, and the Number sorting is the one you would expect.

Using 
* pg `7.4.1`
* postgres `10.0.1`

**Comment by charmander** [comment] 2018-04-14 09:59
int8s are returned as strings by default because JavaScript numbers don’t have enough precision to represent all their values; if you have an int8 value you know won’t exceed `Number.MAX_SAFE_INTEGER`, you can parse it with `parseInt`.

To change the default, see https://github.com/brianc/node-pg-types#use.

**Comment by charmander** [comment] 2018-04-14 09:59
Duplicate of #639

**Closed by charmander** 2018-04-14 09:59 UTC
