### ISSUE TITLE
Can't connect to any Postgres DB on macOS Big Sur and Apple Silicon

### ISSUE THREAD

**Issue by michael** [brianc/node-postgres#2413] opened 2020-11-18 07:22 UTC
Hi there!

Possibly the issue isn't related to node-postures, but I needed a place to start. I'm getting a connection timeout, no matter if I connect to a local Postgres or a remote one. The same setup works perfectly on my old Intel machine. It seems that for some strange reason Node can't talk outside.

I'm running Node.js v14.15.1 and node-postures 7.12.1.

I wonder if anybody running on one of these new Apple M1 laptops was able to connect to Postgres via Node. Maybe you have some pointers. Thanks a lot for the help!

**Comment by brianc** [comment] 2020-11-18 16:47
That's rad you got a new M1 laptop!  I'm waiting for a while to get one, but it's in my sights. 🎯 

As far as this being a node-postgres thing...let me know what you find out.  I __highly__ doubt it's related to this driver as if you're using the pure js version it doesn't do anything out of the normal, and relies an no external libraries for sockets or anything other than what's baked into node.js.  One thing you _could try_ is just connect `net.connect` to the postgres host and port & log out if you get any packets back.  If this _actually is_ an issue with the M1 laptops and node postgres...well well santa might just have to come early for me this year. 😄 though really that's concerning because I don't think there's a "test this w/ an M1 chip" in travis ci.

**Comment by sehrope** [comment] 2020-11-18 17:39
@michael Check if there's additional firewall restrictions put in place by Apple in the latest OS version. They may be limiting outbound TCP connections from unsigned binaries unless you explicitly allow it.

>  I don't think there's a "test this w/ an M1 chip" in travis ci.

@brianc Travis does have arm64 support though :smile: https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by brianc** [comment] 2020-11-18 17:39
> ravis does have arm64 support though

sweet

**Comment by michael** [comment] 2020-11-18 18:15
> That's rad you got a new M1 laptop! I'm waiting for a while to get one, but it's in my sights. 🎯

Yeah, I was surprised it was delivered so fast. Expected it by end of the month. Except for that db issue, everything is working super smooth so far. Love it that there's no fan ever getting off. :)

> As far as this being a node-postgres thing...let me know what you find out. I **highly** doubt it's related to this driver as if you're using the pure js version it doesn't do anything out of the normal, and relies an no external libraries for sockets or anything other than what's baked into node.js. One thing you _could try_ is just connect `net.connect` to the postgres host and port & log out if you get any packets back. If this _actually is_ an issue with the M1 laptops and node postgres...well well santa might just have to come early for me this year. 😄 though really that's concerning because I don't think there's a "test this w/ an M1 chip" in travis ci.

Will try the net.connect thing some time in the next days thanks! I'll keep you posted. :)

**Comment by michael** [comment] 2020-11-18 18:16
> @michael Check if there's additional firewall restrictions put in place by Apple in the latest OS version. They may be limiting outbound TCP connections from unsigned binaries unless you explicitly allow it.

@sehrope Yeah thanks, main firewall is off, but maybe there's something more, haven't actually checked if node is able to talk to anywhere yet.

**Comment by charmander** [comment] 2020-11-18 23:59
> I'm running Node.js v14.15.1 and node-postures 7.12.1.

Node ≥ 14 requires pg ≥ 8.

**Comment by charmander** [comment] 2020-11-19 00:00
Duplicate of #2279

**Closed by charmander** 2020-11-19 00:00 UTC

**Comment by michael** [comment] 2020-11-19 10:49
@charmander Upgrading to pg ≥ 8 did it. Thanks a lot! 👍

**Comment by thesmart** [comment] 2021-02-04 05:00
Is it possible to add a warning message to pg < 8 if running on Node 14, or add a hard requirement to the package?

**Comment by bmxpiku** [comment] 2023-03-30 12:42
@thesmart what if Im facing it with Node 18
"pg": "^8.9.0",
"knex": "^2.4.2",
?

And its very rare... 99.9% of queries pass correctly, but out of the blue one every now and then throws 
```
"stack": "Error: timeout expired\n    at Timeout._onTimeout (/server/node_modules/pg/lib/client.js:106:28)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)"
```
