### ISSUE TITLE
WHERE IN condition

### ISSUE THREAD

**Issue by Flydexo** [brianc/node-postgres#2783] opened 2022-08-14 23:12 UTC
How can I implement the WHERE IN condition because it doesn't seem to work like this
```
const request = `SELECT ${infos.join(",")} FROM global_elements WHERE id in $1`;
return (await pool.query(request, [ids])).rows;
```

**Comment by charmander** [comment] 2022-08-15 01:55
Duplicate of #1452

**Closed by charmander** 2022-08-15 01:55 UTC
Labels: question
