### ISSUE TITLE
error message doesn't say which and line error is generated from

### ISSUE THREAD

**Issue by Rc85** [brianc/node-postgres#1773] opened 2018-11-18 23:15 UTC
A typical error in node-postgres is something like this

```
{ error: syntax error at or near "WHER"
    at Connection.parseE (H:\...\...\node_modules\pg\lib\connection.js:553:11)
    at Connection.parseMessage (H:\...\...\node_modules\pg\lib\connection.js:378:19)
    at Socket.<anonymous> (H:\...\...\node_modules\pg\lib\connection.js:119:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
  name: 'error',
  length: 93,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '57',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1087',
  routine: 'scanner_yyerror' }
```

Is it not possible to identify the file and line number the error is generated from?

**Comment by charmander** [comment] 2018-11-20 23:31
Duplicate of #1762

**Closed by charmander** 2018-11-20 23:31 UTC
