### ISSUE TITLE
Current schema (searchpath) support in connection string

### ISSUE THREAD

**Issue by sscarduzio** [brianc/node-postgres#2629] opened 2021-10-07 08:20 UTC
Why not supporting specifying the default schema within the connection string?

For example, JDBC has the following:

`postgresql://localhost:5432/mydatabase?currentSchema=myschema`

**Comment by sscarduzio** [comment] 2021-10-08 16:20
sorry didn't see that!

**Comment by charmander** [comment] 2021-10-10 21:50
Duplicate of #1123

**Closed by charmander** 2021-10-10 21:50 UTC
