### ISSUE TITLE
connect method failing silently on mac OS

### ISSUE THREAD

**Issue by Prabhakar-17** [brianc/node-postgres#2250] opened 2020-06-23 21:25 UTC
I am trying to connect with postgres, the connect method is failing silently and the code is not executed further(I do not see the 'connected' console log message or any error). I verified the postgres server by connecting through terminal (psql)

Node: v14.4.0
macOS: 10.15.5
pg: 7.12.1

```js
const { Client } = require('pg');

const pgtest = async () => {
    console.log('connecting....')
    const connectionString = 'postgres://postgres:somepwd@127.0.0.1:5432/postgres';
    const cl = new Client(connectionString);
    await cl.connect();
    console.log('connected:: ');
    await cl.end();
}

pgtest();
```

I tried the same code on ubuntu and it works.

**Comment by charmander** [comment] 2020-06-24 17:23
pg ≤ 8.0.2 doesn’t support Node 14. Please upgrade to pg 8.2.1.

**Comment by charmander** [comment] 2020-06-24 17:23
Duplicate of #2226

**Closed by charmander** 2020-06-24 17:23 UTC
