### ISSUE TITLE
Docs: error in async/await transaction example

### ISSUE THREAD

**Issue by Rhymen** [brianc/node-postgres#1931] opened 2019-07-20 12:20 UTC
Hi,

just saw that the example code 'A pooled client with async/await' had an error. Its trying to reference `res.rows`, but res is not defined. Instead rows is being defined by destructuring the return value of the query function.

https://node-postgres.com/features/transactions

Correct code would be:
```
const { Pool } = require('pg')
const pool = new Pool()(async () => {
  // note: we don't try/catch this because if connecting throws an exception
  // we don't need to dispose of the client (it will be undefined)
  const client = await pool.connect()
  try {
    await client.query('BEGIN')
    const queryText = 'INSERT INTO users(name) VALUES($1) RETURNING id'
    const { rows } = await client.query(queryText, ['brianc'])
    const insertPhotoText = 'INSERT INTO photos(user_id, photo_url) VALUES ($1, $2)'
    const insertPhotoValues = [rows[0].id, 's3.bucket.foo']
    await client.query(insertPhotoText, insertPhotoValues)
    await client.query('COMMIT')
  } catch (e) {
    await client.query('ROLLBACK')
    throw e
  } finally {
    client.release()
  }
})().catch(e => console.error(e.stack))
```

**Comment by charmander** [comment] 2019-07-20 16:28
Duplicate of #1622

**Closed by charmander** 2019-07-20 16:28 UTC
