### ISSUE TITLE
ASCII enconding problem

### ISSUE THREAD

**Issue by LuizGMX** [brianc/node-postgres#2207] opened 2020-05-09 16:07 UTC
Hi, the result of a query that cotains a accent comes with a problem, every accent is replaced by a "�".
And when I try to make a select that the clause "where" cotains a accent too, I don't get a return.

**Comment by charmander** [comment] 2020-05-09 18:25
Duplicate of #2203

**Closed by charmander** 2020-05-09 18:25 UTC
