### ISSUE TITLE
Cannot connect local PostgreSQL DB 

### ISSUE THREAD

**Issue by malbruk** [brianc/node-postgres#2279] opened 2020-07-15 17:54 UTC
I connect my PostgreSQL local database in Node.js server using pg.

All worked fine, but suddenly it stopped to work.

This is my code:
`const {Pool} = require('pg')`
`const connectionString = process.env.DATABASE_URL;`
`const ssl = process.env.NODE_ENV == 'production' ? '?ssl=true' : '';`
`const pool = new Pool({`
`    connectionString: connectionString + ssl`
`});`

`const db = {`
`    pool: pool,`
`    test: async () => {`
`        try {`
`            console.log('before connection');`
`            let result = await pool.query('SELECT $1::text as status', ['connected']);`
`            console.log('connected')`
`            return result.rows[0].status;`
`        } catch (error) {`
`            console.error('Unable to connect to the database:', error);`
`            return null;`
`        }`
`    }`
`}`

`module.exports = db;`

It stuck on pool.query. 'before connection' is logged, no error is thrown.

The very same code works fine with my remote db, and I can connect the local db with pgAdmin.

**Comment by charmander** [comment] 2020-07-15 23:21
Which versions of Node and pg are you using?

**Comment by hjr3** [comment] 2020-07-16 00:57
I wonder if `rejectUnauthorized` is being defaulted to `true`.

**Comment by charmander** [comment] 2020-07-16 04:12
@hjr3 It would throw an error instead of getting stuck in that case.

**Comment by malbruk** [comment] 2020-07-16 07:30
> Which versions of Node and pg are you using?

Thanks, that was the problem. I used node version 14. I downgraded to 12 and it's ok now.

**Comment by charmander** [comment] 2020-07-16 18:58
You don’t need to downgrade Node, just upgrade pg to the latest version.

**Comment by charmander** [comment] 2020-07-16 18:59
Duplicate of #2275

**Closed by charmander** 2020-07-16 18:59 UTC
Labels: waiting for more info
