### ISSUE TITLE
Uncaught exception while creating a SSL connection

### ISSUE THREAD

**Issue by chris--young** [brianc/node-postgres#2307] opened 2020-08-12 01:05 UTC
I found an error in `Client.connect()` that isn't passed to the callback and can't be caught. If one of the `ca`, `key`, or `cert` strings you use while creating an SSL connection is not a valid certificate your program will crash.

This error should be properly handled and recoverable. An easy fix is to add a try catch around the `tls.connect()` call on line 92 of `lib/connection.js` and return while emitting the caught error. Then the error will gracefully be passed to the connection callback and the user can recover without their program crashing.

I'm happy to open a pr with the fix if you want.

This is the error...
```
_tls_common.js:129
      c.context.setCert(cert);
                ^

Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:129:17)
    at Object.connect (_tls_wrap.js:1567:48)
    at Socket.<anonymous> (/Users/chris/Desktop/pg_error/node_modules/pg/lib/connection.js:92:23)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

This code will reproduce it...
```
const pg = require('pg');

const config = {
  host: 'redacted',
  database: 'redacted',
  user: 'redacted',
  password: 'redacted',
  ssl: {
    ca: 'foo',
    key: 'foo',
    cert: 'foo'
  }
};

const client = new pg.Client(config);

function callback(err) {
  if (err)
    return console.error('CALLBACK ERROR:', err); // this line should log the error but doesn't

  client.end();
}

try {
  client.connect(callback);
} catch (err) {
  console.error('CAUGHT ERROR:', err); // this line wont catch the error either
}
```

**Comment by Lewiscowles1986** [comment] 2020-08-12 04:54
Surely the server in the case of SSL should be configured for only SSL for data-security? Why would you recover rather than fix?

**Comment by Lewiscowles1986** [comment] 2020-08-12 05:01
Also, is this note similar to https://github.com/brianc/node-postgres/issues/2004

**Comment by chris--young** [comment] 2020-08-12 06:46
Yea this is the same issue. I didn't see that other issue when I searched before.

My project has a rest api endpoint that allows users to perform a query on a database they provide the connection information for. Because there is no way for me to recover from this error, if a user attempts to use that endpoint while providing an invalid value for their ssl certificate it takes down the whole server. If this error was properly handled I could simply send them back a 400 response and let them know their input was bad.

**Comment by charmander** [comment] 2020-08-12 13:03
Duplicate of #2004

**Closed by charmander** 2020-08-12 13:03 UTC
