### ISSUE TITLE
client.connect() and pool.connect() hang under node 14.

### ISSUE THREAD

**Issue by markddrake** [brianc/node-postgres#2179] opened 2020-04-26 06:18 UTC
await client.connect() and await pool.connect() hang indefinitely  with node 14. (I'm using the docker image node:latest in my testing. With the image node:13 everything works as expected...

This is true even with the simple connection examples in the node documentation.

**Comment by brianc** [comment] 2020-04-26 06:23
What version of the lib do you have installed? We just fixed an issue in
the most recent point release. (8.0.3)

**Comment by jarindr** [comment] 2020-04-26 13:29
@markddrake MAN YOU SAVED MY 40 HRS DEBUGGING THE WHOLE PG LIB, thanks ! lol

**Comment by charmander** [comment] 2020-04-26 13:36
Duplicate of #2177

**Closed by charmander** 2020-04-26 13:36 UTC

**Comment by markddrake** [comment] 2020-04-26 21:48
@brianc 

    "pg": "^7.18.2",
    "pg-copy-streams": "^2.2.2",
    "pg-query-stream": "^3.0.6",

I also encountered it with 8.0.3

**Comment by markddrake** [comment] 2020-04-26 21:49
> @markddrake MAN YOU SAVED MY 40 HRS DEBUGGING THE WHOLE PG LIB, thanks ! lol, 8.0.3 works

Your welcome, I wish I could get the 2 days I spent tearing my code apart back :)
