### ISSUE TITLE
pg hanging when I call client.connect()

### ISSUE THREAD

**Issue by gibran-shah** [brianc/node-postgres#2275] opened 2020-07-13 02:50 UTC
Hello,

I recently had to upgrade my node.js version for my vue.js application (node.js on the backend) from v13.5.0 to v14.5.0. I reinstalled all my node packages, upgrading the ones I had to upgrade, and now the application hangs on all DB calls. We are using pg for our database calls. I upgraded pg to version 7.18.2.

Our initialization code looks like this:

this.pg = require('pg');
...
      this.client = new this.pg.Client({ 
        application_name: 'Back end',
        ssl: {
          rejectUnauthorized: false
        }
      });
this.initPromise = this.client.connect();

I put console logs around the call to this.client.connect() as follows:

console.log('before');
this.initPromise = this.client.connect();
console.log('after');

'after' never prints out.

Does anyone know why it hangs now that I've upgrade my node version?

**Comment by geoffsmith** [comment] 2020-07-13 13:22
This maybe? https://github.com/brianc/node-postgres/issues/2170

**Comment by gibran-shah** [comment] 2020-07-13 17:57
I upgraded to pg v8.3.0 and it worked. Seems that npm install pg doesn't install the latest version after all. npm install pg@latest does.

**Comment by charmander** [comment] 2020-07-14 05:23
Duplicate of #2250

**Closed by charmander** 2020-07-14 05:23 UTC
