### ISSUE TITLE
connection-parameters.js does not support currentSchema

### ISSUE THREAD

**Issue by plcstpierre** [brianc/node-postgres#1023] opened 2016-05-17 01:27 UTC
http://stackoverflow.com/questions/4168689/is-it-possible-to-specify-schema-when-connecting-to-postgres-with-jdbc

neither does pg-connection-string

**Comment by vitaly-t** [comment] 2016-05-17 16:52
The feature was introduced in PostgreSQL 9.4:
```
postgres://username:password@host:port/database?currentSchema=myschema
```

Both [pg-connection-string](https://github.com/iceddev/pg-connection-string) and this library would need to be updated.

**Comment by plcstpierre** [comment] 2016-05-20 16:22
Do you have a link for the postgres protocol? I would like to give it a try.

**Comment by elmigranto** [comment] 2016-07-26 16:39
> Do you have a link for the postgres protocol?

@plcstpierre Is this what you are asking about?
https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by plcstpierre** [comment] 2016-09-01 23:54
Nope. I mean the low level stuff. What the client is supposed to do when it receive a schema in the string?

**Comment by elmigranto** [comment] 2016-09-02 04:15
It supposed to pass it down to server to figure out.

**Comment by charmander** [comment] 2017-08-21 02:43
Duplicate of #1123

**Closed by charmander** 2017-08-21 02:43 UTC
